### ISSUE TITLE
Cookie notice not being blocked on dailymail.co.uk and makes the website unusable

### ISSUE THREAD

**Issue by PhoenixFossGR** [easylist/easylist#17429] opened 2023-09-28 02:55 UTC
#### List the website(s) you're having issues with:

`https://www.dailymail.co.uk/home/index.html`

#### What happens?

When someone enters the Daily Mail website, there is a large cookie notice on the bottom of the screen that is not being blocked. The website is completely unusable if the cookie notice is not interacted with.

#### Screenshot(s) 

![Screenshot from 2023-09-28 05-52-53](https://github.com/easylist/easylist/assets/123986260/3612ed82-22af-4a38-a3e7-c88d917ceb27)

#### Filter lists you're using:

EasyList Cookie

#### Your settings:

- OS/version: Fedora Silverblue 38
- Browser/version: Firefox 118.0
- Ad block extension/version: uBlock Origin 1.52.2

**Comment by GeorgeGR21** [comment] 2023-11-01 12:07
The same notice is back.
![Screenshot from 2023-11-01 14-06-30](https://github.com/easylist/easylist/assets/123986260/a9eec6f9-2c2d-4c98-99ea-fac44e02c329)

**Comment by Khrin** [comment] 2023-11-12 19:30
Closing here. Seems to be fixed already.

**Closed by Khrin** 2023-11-12 19:30 UTC

**Comment by ryanbr** [comment] 2023-11-14 01:19
I'm unable to see it, is the `EasyList/uBO – Cookie Notices` enabled? cc @stephenhawk8054

**Comment by stephenhawk8054** [comment] 2023-11-14 03:32
I can't reproduce either

Can you open new tab > reproduce the issue and on that page > click on uBO icon > &#128172; [Report button](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-tools) > scroll to the bottom > click on `Troubleshooting Information` and copy paste it here?
