### ISSUE TITLE
Please add ads.tiktok.com to the popover allowlist

### ISSUE THREAD

**Issue by iplaces** [easylist/easylist#18939] opened 2024-04-09 08:49 UTC
#### List the website(s) you're having issues with:

ads.tiktok.com

#### What happens?

Now the popover of ads.tiktok.com will be blocked, affecting the normal use of the website. It has been removed by mistake  in this commit https://github.com/easylist/easylist/commit/8acc08fd60d6966bb354df1d4c9657be3756368d#diff-47b4e53aead2fc18b258118b13c7807652e1c3b839f5511edb60af30fc2407daL28

#### Your settings:

- OS/version: 
- Browser/version: 
- Ad block extension/version: 

@@||ads.tiktok.com^$popup

**Comment by Daxy7** [comment] 2024-04-12 11:17
Accessing `https://ads.tiktok.com/` itself redirects to `https://ads.tiktok.com/i18n/home` in my case.
He could be trying to send someone this link, it gets blocked automatically in uBlock Origin due to strict blocking enabled.

**Comment by Yuki2718** [comment] 2024-04-12 13:08
Still no idea why access `https://ads.tiktok.com/`.

**Comment by Daxy7** [comment] 2024-04-12 18:05
For businesses, otherwise turn easylist off per worker in the adblocker settings.
Why does he state that the popover is apparent when the commit he's showing removes it [cleanup]?
https://github.com/easylist/easylist/commit/8acc08fd60d6966bb354df1d4c9657be3756368d#diff-47b4e53aead2fc18b258118b13c7807652e1c3b839f5511edb60af30fc2407daL28

**Comment by Khrin** [comment] 2024-04-15 21:50
It seems that OP has lost all interest in this topic. (or never really had it in the first place).

Closing here.

**Closed by Khrin** 2024-04-15 21:50 UTC
Labels: Need more info, Easylist

**Comment by Yuki2718** [comment] 2024-04-16 04:33
@monzta Can you reproduce https://github.com/easylist/easylist/commit/24e7a28b12179b69c5b7d61edeed6814472a6e72 now?

**Comment by monzta** [comment] 2024-04-16 16:03
@Yuki2718 Not the specific case on facebook but if I want to open a link to https://ads.tiktok.com/ in an email, it gets blocked now.

**Comment by Yuki2718** [comment] 2024-04-16 16:17
So should it be unblocked?

**Comment by monzta** [comment] 2024-04-16 17:25
I would say so. I don't expect it to cause harm if added.
