### ISSUE TITLE
Usernames wrongly removed from some forum software

### ISSUE THREAD

**Issue by dikrek** [easylist/easylist#15430] opened 2023-04-04 19:05 UTC
### List the website(s) you're having issues:

gearspace.com - it's a famous forum for pro audio

for example, this page
https://gearspace.com/board/high-end/1402752-difference-extending-xlr-cables-vs-long-cables.html 

### What happens?

easylist removes the usernames from each post, in addition to ads in the site. Disabling easylist removes the issue.

### List Subscriptions you're using:

adguard, OISD

### Your settings

- OS/version: Win11, latest version
- Browser/version: Edge, latest version
- Adblock Extension/version: Ublock Origin, latest rev

### Other details:

Same issue on iOS with wipr (which uses easylist as well).

HOWEVER - on Firefox the issue isn't seen, with the same blocklists, same blocker.

**Comment by dikrek** [comment] 2023-04-04 19:14
![Screenshot 2023-04-04 200740](https://user-images.githubusercontent.com/24657745/229896583-87741888-f660-4735-ab96-dd3b39e2f99f.png)
![Screenshot 2023-04-04 200740](https://user-images.githubusercontent.com/24657745/229896585-fd79f91b-aab4-48a1-b718-37e92aa87a96.png)

**Comment by dikrek** [comment] 2023-04-04 19:15
pictures with/without the issue
![Screenshot 2023-04-04 200740](https://user-images.githubusercontent.com/24657745/229896961-8edba2a6-ef47-4150-9798-d0f8ff497e29.png)
![Screenshot 2023-04-04 200708](https://user-images.githubusercontent.com/24657745/229896965-fb4badb0-bc04-4cb0-86f2-6fca1a60a573.png)

**Comment by ryanbr** [comment] 2023-04-08 23:52
Looks fine here, not able to reproduce. @dikrek

**Comment by ryanbr** [comment] 2023-04-11 11:12
Closing ticket, still seems fine

**Closed by ryanbr** 2023-04-11 11:12 UTC
