### ISSUE TITLE
xnxx.com: cookies

### ISSUE THREAD

**Issue by Bug-Cache** [easylist/easylist#16876] opened 2023-07-28 02:27 UTC
![image](https://github.com/easylist/easylist/assets/98657967/78214f68-c786-4f2a-a3aa-c036bc15ba60)

https://www.xnxx.com/

**Comment by yokoffing** [comment] 2023-08-18 04:09
Fixed now? Can't reproduce. Please close if fixed.

**Closed** 2023-08-27 08:54 UTC
