### ISSUE TITLE
Issue with Linkedin site

### ISSUE THREAD

**Issue by keul** [easylist/easylist#5007] opened 2020-02-28 10:09 UTC
### List the website(s) you're having issues:

https://www.linkedin.com/

### What happens?

Linkedin started to include resources on cedexis.net, which is blocked by rules.
So uBlock Origin with this list enabled is making Linkedin not working anymore.

![Schermata 2020-02-28 alle 11 04 40](https://user-images.githubusercontent.com/284924/75539243-3864c880-5a1a-11ea-89dd-019d9da5fcc9.png)

### List Subscriptions you're using:

uBlock Origin
Rule has been find inside EasyPrivacy

### Your settings

- OS/version: MacOS 10.14.6
- Browser/version: Firefox 73.0.1
- Adblock Extension/version: 1.25.0

### Other details:

Maybe this?

https://github.com/easylist/easylist/blob/e2c42b73efbb5b58125c9964f28c4bfcd2136bc9/easyprivacy/easyprivacy_trackingservers.txt#L434

**Comment by llacb47** [comment] 2020-02-28 12:20
Already fixed by uBo, update your lists.

**Comment by Khrin** [comment] 2020-02-28 12:31
> 
> 
> Already fixed by uBo, update your lists.

@llacb47 So what?

**Comment by llacb47** [comment] 2020-02-28 12:32
It is an issue caused by uBo CNAME uncloaking... https://github.com/uBlockOrigin/uAssets/issues/7012

**Closed** 2020-02-28 12:38 UTC
Labels: Invalid, uBO-Specific

**Comment by krystian3w** [comment] 2020-02-28 13:36
valid, DNS glitch site

@mapx- similar bug on "Bloomberg"
