### ISSUE TITLE
Login pages not working

### ISSUE THREAD

**Issue by runboy93** [easylist/easylist#842] opened 2018-01-15 06:58 UTC
I'm using EasyPrivacy + Easylist combination on uBlock Origin 1.14.25rc0, Mozilla Firefox ESR.

These pages won't load after press "log in"

https://oneplus.net/fi/account/sign-in

https://eu.wargaming.net/support/login

**Comment by ryanbr** [comment] 2018-01-15 08:34
Works fine here? I don't have a valid login, but reported that I had incorrect details

**Comment by runboy93** [comment] 2018-01-22 12:13
Atleast with this:
https://eu.wargaming.net/support/login

Just press "log in", without login information. Same effect, load notification will get stuck for some reason.

**Comment by runboy93** [comment] 2018-02-04 12:52
https://eu.wargaming.net/id/signin/

**Comment by runboy93** [comment] 2018-02-04 13:04
https://oneplus.net/fi/account/sign-in

And this page should show Google "reCAPTCHA" during log in, maybe whitelist?

**Comment by ryanbr** [comment] 2018-02-04 21:09
Given I cant reproduce it, and unless someone else can there isn't much I'll do.

**Comment by ryanbr** [comment] 2018-02-28 08:29
Closing,  Fixed the social icons not showing on oneplus.net.

**Closed by ryanbr** 2018-02-28 08:29 UTC
