### ISSUE TITLE
yandex.com

### ISSUE THREAD

**Issue by DandelionSprout** [easylist/easylist#6621] opened 2020-12-05 11:13 UTC
### List the website(s) you're having issues:

`https://yandex.com/weather/trondheim`

### What happens?

Their `Yandex Direct` ads seem to have got around the existing entries in EasyList, AdGuard Base, uAssets Main, RU AdList **and** AdGuard Russian Filter.

### List Subscriptions you're using:

![image](https://user-images.githubusercontent.com/22780683/101241036-0728cf80-36f3-11eb-929b-6b14d484ddec.png)

### Your settings

- OS/version: Windows 10 October 2020 Update
- Browser/version: Chrome 87.0.4280.88 x64
- Adblock Extension/version: uBO 1.31.3b1 + IDCAC 3.2.6

### Other details:

Notably, the ads do *not* show up the first time the page is loaded, but only on subsequent reloads.

A proper fix is beyond my abilities to write, since the ads seem to be embedded within `||yandex.com/weather/_cry^$image,script`, the blockage of which also blocks the forecast cards for individual upcoming days.

![image](https://user-images.githubusercontent.com/22780683/101240930-ba44f900-36f2-11eb-9c1e-6b52c2be9290.png)

**Comment by THEtomaso** [comment] 2020-12-05 15:19
At least, this seems to work, at the moment:
```
yandex.com##.mySSl
yandex.com#?#.card:-abp-has(.mySSl)
```

**Comment by THEtomaso** [comment] 2020-12-05 16:34
> llacb47 reacted with thumbs down emoji

@llacb47:
If you were unable to reproduce, then read what DandelionSprout wrote about having to reload the page.

**Comment by llacb47** [comment] 2020-12-05 18:22
Sorry, my comment didn't go through for some reason.

This cannot be fixed in easylist. See here: `https://forums.lanik.us/viewtopic.php?f=62&t=44643#p154474`

**Comment by DandelionSprout** [comment] 2020-12-05 18:27
Over on Slack, it seems that RU AdList and AdGuard believes that AdGuard changes their element names far too frequently for typical filterlists to block them, and they recommended AdGuard Extra and/or RU AdList Counters (the latter of which I thought was tracker-specific).

I'll keep this open for a couple days in case e.g. Khrin, uAssets, or whoever else want to try their luck at this, after which I'd probably close this.

**Comment by dimisa-RUAdList** [comment] 2020-12-05 18:46
Yandex changes not only the names of elements, but also changes their position, network requests responsible for embedding them, and much more.

As for ABP-users, RU AdList Counters will only partially help them. Due to the lack of functionality similar to uBO in this extension, they are recommended to use RU AdList JS Fixes + RU AdList CSS Fixes: https://github.com/easylist/ruadlist/wiki/RU-Adlist-links

For uBO-users, RU AdList Counters is enough.

**Closed** 2020-12-14 03:31 UTC
