### ISSUE TITLE
Easylist filter based on image dimension filters too much

### ISSUE THREAD

**Issue by balsamiqFlorian** [easylist/easylist#187] opened 2016-11-01 18:22 UTC
Hi,
I encountered the the issue that easylist filters images based on their dimensions. This causes that my correct images that are not ads get filtered. The particular filter is:
"-300x600."

I have seen that you also have variations of it with "ad" tags. This reference is needed for items like mosaic galleries which display images in various sizes.

Please remove the items from your list or refine them. Currently they catch too much.

**Comment by febsn** [comment] 2017-05-05 14:17
Probably a duplicate of #79

**Closed** 2019-09-25 10:45 UTC
