### ISSUE TITLE
VG.no - Adblock detection script issue (EasyList)

### ISSUE THREAD

**Issue by THEtomaso** [easylist/easylist#3924] opened 2019-08-15 22:14 UTC
### Affected site:
`https://www.vg.no/`

### Issue:
Blocked adblock detection script results in survey popup.

### Example:
`https://www.vg.no/sport/fotball/i/MRpo80/`

### Screenshot:
![filterissue-vg2](https://user-images.githubusercontent.com/9382674/63130421-a683f980-bfba-11e9-8966-74ea3e7ad36f.jpg)

### Problem filter:
* EasyList

### Problem rule:
`/advert.$domain=~advert.ae|~advert.ee|~advert.io|~motortrader.com.my`

### Blocked script:
`https://advert.vg.no//check.js`

### Possible fix:
```
- /advert.$domain=~advert.ae|~advert.ee|~advert.io|~motortrader.com.my
+ /advert.$domain=~advert.ae|~advert.ee|~advert.io|~motortrader.com.my|~vg.no
```

--

### System info:
* OS/version: Windows 8.1 Pro (x64)
* Browser/version: Pale Moon v28.6.1 (x64)
* Adblock Extension/version: uBlock Origin v1.16.4.11 (XUL)

**Comment by krystian3w** [comment] 2019-08-16 07:21
PS. hard to reproduce - subdomain can change on clear cookies to:

`advert.vg.no`
`ads.vg.no`
`advertisement.vg.no`

**Comment by Khrin** [comment] 2019-08-16 09:27
It can't be added to easylist. Also, for what I can see, this anti adblock popup can even be closed by the user.

**Closed by Khrin** 2019-08-16 09:27 UTC

**Comment by THEtomaso** [comment] 2019-08-16 12:19
> It can't be added to easylist.
The rule is already present, with exceptions for four different sites.

**Comment by Khrin** [comment] 2019-08-16 12:27
That exceptions are required because otherwise affected sites would be broken, not for blocking anti adblock stuff. I don't know norwegian, but I don't see anything broken here by this filter and an exception for blocking the anti adblock popup here can't be added.
