### ISSUE TITLE
cmp.osano.com

### ISSUE THREAD

**Issue by arlogilbert** [easylist/easylist#7265] opened 2021-02-22 15:02 UTC
### List the website(s) you're having issues:

https://www.osano.com

### What happens?

Consent management dialogs, privacy policy links, and CCPA do-not-sell requests are blocked.

### List Subscriptions you're using:

Easylist

### Your settings

- OS/version: 
- Browser/version: Brave (latest)
- Adblock Extension/version: Built in

### Other details:

Blocking Osano violates the privacy rights of users. When the Osano consent dialogs are blocked, users are not able to modify their preferences, users are not able to access the privacy policy of the website, and they are unable to access the CCPA mandated "do not sell" dialog. Across numerous ad blockers and browsers including Brave, users are notified that they will no longer view "ads and trackers" but they are never notified that consent management dialogs will be blocked. On many sites that utilize Osano, blocking the consent management dialog causes more tracking related scripts to load which means that any ad blocker which is blocking cmp.osano.com is actually causing more 3rd party resources to load and causing more IP address sharing to occur. The reason for this is that Osano does not operate simply as a popup, rather Osano is a filter that prevents third party scripts, iframes, and cookies from loading until the end user has opted for the appropriate category of consent. Osano does not track individual users

**Comment by EricRa** [comment] 2021-02-23 23:44
I was curious about this one so went to osano.com to test some things.

This domain is not listed in EasyList, but it does have two listings in the EasyPrivacy list.

It sounds like you are more concerned with functionality on third-party sites which use Osano than the actual osano.com homepage.  Is that accurate?  If so, it would be helpful to give an example URL where calls are made to the Osano domain from a third-party site.  This way, the list maintainers can see what is being blocked and if it is appropriate.

Concerning the osano.com home page itself. the site utilizes third party trackers from Google, LinkedIn, and NewRelic (among others), and these all seem like appropriate things for privacy lists to be blocking.

Again, I think if you gave an example URL of a site where Osano domain calls are being made and (improperly) blocked, that would help the maintainers determine whether the blocking is appropriate.  It could at least lead to more narrow rules for the domain if some things are being inappropriately blocked.

**Comment by arlogilbert** [comment] 2021-02-24 00:27
Hi @EricRa thanks for looking at this. 

osano.com uses our own Osano Consent Manager. When cmp.osano.com is blocked, you will not see a cookie popup and will not see the little cookie icon appear in the bottom left corner. We do have Google, LinkedIn, NewRelic and many others on that page, however we do not load those items until an individual has consented based on their regional law. 

Because the cmp.osano.com domain is blocked, our policies in the CMP product are unable to enforce the policies. If the Osano CMP does load, then those tags and scripts can not execute until the proper consent level has been granted by the user.

If you take a look at the source for the page you'll see a reference to cmp.osano.com in the document - that is blocked - Pat  & Rbrowne over at Brave pointed me here, I'm not sure which lists contain cmp.osano.com but any lists that contain it are impacting a user's ability to edit their preferences.

**Comment by EricRa** [comment] 2021-02-24 00:57
Hi Arlo,

I should make it clear that I am not a maintainer of this list.  I was just trying to help parse out the issue a bit so the issue can be addressed when the maintainers have time.

I have to say that from an end-user perspective, the behavior of the osano.com home page seems to include exactly the type of content I would want a list to block for me.  That is, when loading the site with no add-ons or tracking protection active, I am automatically opted into third-party marketing and personalization using third-party trackers by simply remaining on the page.  I have to click a not-entirely-obvious cookie icon to manually opt out of these things.  All of the third-party tracking is enabled without me actively clicking anything.

So from my perspective, this is precisely the type of content that should be blocked, but it will be up to the maintainers of the list to make that determination.

The reason I recommended including a URL to a third-party site that calls the Osano domain is that it is possible for the list maintainers to make the blocking more specific and granular if they determine the blanket block on the domain is too broad and causing a bad outcome.

**Comment by arlogilbert** [comment] 2021-02-24 01:28
I’m not debating whether a particular tracker is beneficial or not. You are likely in a region that has less restrictive laws, if you arrive from a country that does has more restrictive rights, those items will not load without proactive consent... but I’m not complaining about easylist blocking the trackers, I’m concerned about it blocking cmp.osano.com which serves the consent dialogs required to comply with various privacy laws.

I think the confusion here is that we both make the consent product and I am showing you our website we’re we are also users of the consent product.

If you’re not the maintainer, am I on the wrong repo or are you just chiming in to discuss?

-Arlo
________________________________

**Comment by EricRa** [comment] 2021-02-24 01:41
You're in the right place, but you're correct I'm just chiming in, and the list maintainers need to make the determination.

I was just trying to help parse the issue and to suggest that you provide an example URL that shows where the problem is actually occurring, as I thought this would help you get to a resolution more quickly.

**Comment by ryanbr** [comment] 2021-02-28 01:18
Note, this isn't blocked in Easylist. It's blocked via Easyprivacy (a privacy list)

We block NewRelic and other tracking scripts and domains. The user isn't (doesn't need to) consenting to anything that we're already blocking. 

A quick check of cmp.osano.com:

```
user agent checks.
cookie sets/checks.
Local Storage
```

Also note of what we're already blocking, not just specifically targeting cmp.osano.com, see: https://github.com/easylist/easylist/blob/master/easyprivacy/easyprivacy_specific.txt#L2801  and other consent trackers. cmp.osano.com is no different from these domains we're already blocking.

**Comment by arlogilbert** [comment] 2021-02-28 01:51
Are you aware that numerous browsers and ad blockers deploy easy privacy without notifying the end user?

What is the criteria for the allowlist?

-Arlo
________________________________

**Comment by ryanbr** [comment] 2021-02-28 02:13
That is up to the extensions, whether to make a privacy-oriented list default or not.  If a extension or browser wants to improve privacy for the enduser then including Easyprivacy, its up to them. 

When scripts/sites/domains stop tracking or monitoring/ privacy checks endusers, then it would be removed.

**Comment by arlogilbert** [comment] 2021-02-28 02:16
Can you please clarify what the criteria are for inclusion in the blocklist?

-Arlo
________________________________

**Comment by ryanbr** [comment] 2021-02-28 02:44
I'm not going to repeat what has already been stated (as show as above). Consent trackers from one company to another is no different (again, as shown as above)

We won't create a separate rules for osano.com and a rule for everyone else, if there is no further input here, we could probably close this ticket.

**Closed by ryanbr** 2021-02-28 02:44 UTC

**Comment by arlogilbert** [comment] 2021-02-28 04:03
Ryan,

You listed 3 things from a “quick look” without evaluating actual functionality.

If you are adding items to the list with the same lack of specifics then it seems fair to ask what the criteria are.

It sets a cookie? Yes but not an identifiable cookie. You don’t block everything that sets cookies. In fact you have many items on the allow list that do exactly that and also track referrers and more.

It looks at the browser user agent? Yes for the purpose of determining whether to polyfill support for IE11. Is the suggestion that any script that is cross browser compatible and evaluates the user agent to deliver compatible code is a privacy violation? Is every website with Modernize a privacy risk?

I asked a straight forward question regarding the specific criteria for inclusion in the block list. If you don’t know the answer because you don’t do any diligence before adding items to the block list then just say so.

If you know the answer and you have some specific criteria and findings regarding our script then please answer my question so we can either adjust our code or pursue other avenues towards ensuring compliance of our customers.

Your employer asked me to contact you here (and yes I noticed that you were copied on the emails with your corporate email) so I assume you are not unclear about the specific concerns and understand why we are concerned. You aren’t just a list maintainer, you are also responsible for its distribution which is a very different set of circumstances.

Were your list opt-in I wouldn’t take issue, but your list is not opt in for many users who consume the list (such as at your employer), in fact many of them are not even aware that consent, notices, and disclosures are being blocked or that they are even consuming your list.

The script you are blocking does a lot more than consent. Blocking the Osano CMP means you are also blocking do-not-sell requests and hiding legally mandated disclosures regarding cookies and privacy policies.

I’m not going to just go away and forget the issue because you are frustrated at my polite and specific questions (or close the issue) regarding the list that you maintain which impacts millions of website’s ability to comply with myriad privacy laws (not just GDPR)

-Arlo
________________________________

**Comment by ryanbr** [comment] 2021-02-28 04:44
From the issue report: 

`If a site implements any tracking or monitoring, UA/IP/Geo checks, browser detection, analytics, telemetry, linking to third-partys, pixels, referrers, fingerprinting, event/perf logging etc. Regardless how helpful or needed the script(s) are, it will be blocked in Easyprivacy. Privacy comes first and the block on these scripts will remain in place.`

This is covered by consent trackers, including osano (but not exclusive too)
