### ISSUE TITLE
https://investor.vanguard.com/etf/profile/VBR - missing elements

### ISSUE THREAD

**Issue by aperezdc** [easylist/easylist#4129] opened 2019-10-07 17:18 UTC
### List the website(s) you're having issues:

https://investor.vanguard.com/etf/profile/VBR

### What happens?

Some non-ad images are missing, for example the logo at the top-left, and most of the page content is gone—I suspect some content is loaded using XHRs which get blocked.

### List Subscriptions you're using:

https://easylist-downloads.adblockplus.org/easylist_min_content_blocker.json

### Your settings

- OS/version: GNU/Linux
- Browser/version: GNOME Web (a.k.a. Epiphany) version 3.34
- Adblock Extension/version: n/a

### Other details:

In [this bug report](https://gitlab.gnome.org/GNOME/epiphany/issues/967) I have attached a log of the elements being blocked (see first comment).

**Comment by peace2000** [comment] 2019-12-08 15:32
I did not see any difference with or without an anblocker. Is this problem still in effect or has it been fixed already? If the problem is still there, post a screenshot?

**Comment by mcatanzaro** [comment] 2019-12-08 16:58
Yes, problem is still valid.

Broken page with EasyList enabled:

![Screenshot from 2019-12-08 10-55-56](https://user-images.githubusercontent.com/1424966/70392826-5dace200-19a9-11ea-8fb2-72a7352aae5c.png)

Without EasyList:

![Screenshot from 2019-12-08 10-56-37](https://user-images.githubusercontent.com/1424966/70392847-92209e00-19a9-11ea-8d2b-0ada987979c8.png)

**Comment by mcatanzaro** [comment] 2019-12-08 17:00
> https://easylist-downloads.adblockplus.org/easylist_min_content_blocker.json

(Note, since WebKit only supports JSON filters, this is the only filters list we have tested.)

**Comment by mcatanzaro** [comment] 2019-12-08 17:01
Tested with both WebKitGTK 2.26.2 and 2.27.3, but changes to this code in WebKit are quite rare so our result *should* be the same in recent versions of Safari.

**Comment by peace2000** [comment] 2019-12-08 20:49
What adblocker software is being used?

**Comment by mcatanzaro** [comment] 2019-12-09 16:51
Epiphany web browser, which uses WebKitUserContentFilter, described at https://webkit.org/blog/3476/content-blockers-first-look/. If you don't want to try Epiphany, it should be possible to reproduce using Safari.

**Comment by mcatanzaro** [comment] 2019-12-09 16:53
Note the "adblock software" is built into WebKit (and, accordingly, WebKit-based browsers). It's different from Chrome or Firefox adblock extensions in that the adblocker is provided by the browser, so there is no third-party adblock extension involved.

**Comment by peace2000** [comment] 2019-12-09 19:07
I run Lubuntu on virtual machine w/ Epiphany. I can reproduce the problem but I cannot find a logger that logs blocked elements.

**Comment by mcatanzaro** [comment] 2019-12-09 20:34
Thanks for testing! Use Ctrl+Shift+I to open the web inspector, and you can see which elements are being blocked:

![Screenshot from 2019-12-09 14-28-09](https://user-images.githubusercontent.com/1424966/70470212-28c78a80-1a90-11ea-966f-1d8464c2090b.png)

However, as far as I'm aware, WebKit provides no way to figure out which particular rule is responsible for blocking the load. (Otherwise, we'd have reported which one it is.)

> I also cannot find any options concerning lists being used.

It's not user-visible, but there's a setting for developers:

```
$ gsettings get org.gnome.Epiphany content-filters
['https://easylist-downloads.adblockplus.org/easylist_min_content_blocker.json']
$ gsettings set org.gnome.Epiphany content-filters "['https://example.com/whatever', 'https://example.com/something-else']"
$ gsettings reset org.gnome.Epiphany content-filters
```

You can also use the dconf-editor application.

**Comment by peace2000** [comment] 2019-12-13 17:28
I tried but just couldn't figure it out what is the problematic rule.

`WebKit provides no way to figure out which particular rule is responsible for blocking the load.`

That's definetely a big problem. I tried to search through that .json list but couldn't find anything that could be related to those blocked elements in Epiphany's inspector...

**Comment by mcatanzaro** [comment] 2019-12-14 00:35
Thanks for looking into it.

> Webkit should be more informative.

It might not be technically-possible... it uses some sort of optimized bytecode. At least a debug mode would be nice to have.

I wonder if I can "bisect" the file by successively removing half the rules. Let's see what happens if I try.

**Comment by mcatanzaro** [comment] 2019-12-14 01:44
Yeah this might work. The bad rule is somewhere between line 300000 and line 400000. Let's see if I can find it....

**Comment by mcatanzaro** [comment] 2019-12-14 02:18
Found the bad rule. It's at line 356706 of easylist_min_content_blocker.json:

```
	{
		"trigger": {
			"url-filter": "^https?://.*",
			"resource-type": [
				"image",
				"raw"
			],
			"load-type": [
				"third-party"
			],
			"if-top-url": [
				"^[^:]+:(//)?([^/]+.)?rd\\.com([^-_.%a-z0-9].*)?$"
			]
		},
		"action": {
			"type": "block"
		}
	},
```

[Here is the easylist_min_content_blocker.json](https://github.com/easylist/easylist/files/3963333/easylist_min_content_blocker.json.txt) that I used to debug. I had to add a .txt extension to attach it to GitHub.

**Comment by peace2000** [comment] 2019-12-14 09:53
Good that you found. Unfortunately I don't understand anything about .json adblocking rules so I don't know what kind of pull request / whitelist rule should be made.

But I can confirm your finding. Tested by removing that rule and now that site works on Epiphany.

@Khrin @ryanbr

**Comment by peace2000** [comment] 2019-12-14 09:56
Good that you found it. Unfortunately I don't understand much about .json adblocking rules so I don't know what kind of pull request / whitelist rule should be made.

@Khrin @ryanbr

**Comment by monzta** [comment] 2019-12-17 17:05
@aperezdc This should fix t: https://hg.adblockplus.org/contentblockerlists/rev/4ac55c6f54f8 Pleasy try again with a freshly downloaded json. 

@mcatanzaro Thanks for pointing out the responsible rule!

**Comment by mcatanzaro** [comment] 2019-12-17 17:36
Confirmed fixed, thanks!

Note @aperezdc is out of office right now so I'm not sure how quickly he'll respond, but he opened this issue at my suggestion, so you can safely close it.

**Closed** 2019-12-17 17:42 UTC

**Comment by aperezdc** [comment] 2019-12-29 18:32
Thanks a lot @mcatanzaro and @monzta for finding the cause and fixing it :hugs:
