### ISSUE TITLE
kaspersky.com & live-streaming.pl

### ISSUE THREAD

**Issue by hawkeye116477** [easylist/easylist#2922] opened 2019-02-27 12:26 UTC
### List the website(s) you're having issues:
`https://www.kaspersky.com/anti-ransomware-tool#form-section`

### What happens?
EasyPrivacy blocks form.

### List Subscriptions you're using:

EasyList, EasyPrivacy

### Your settings

- OS/version: Manjaro 18.0.3 Illyria
- Browser/version: Vivaldi 2.3.1440.57
- Adblock Extension/version: Nano Adblocker v1.0.0.89

### Other details:

Problem is with `||marketo.com^$third-party`.
![screenshot_20190227_131901](https://user-images.githubusercontent.com/19818572/53490083-16490b00-3a93-11e9-92e8-791f9e42d5a3.png)

**Comment by THEtomaso** [comment] 2019-03-16 17:24
Confirmed.

Other filters blocking it:
* AdGuard Tracking Protection filter (a.k.a. 'AdGuard Spyware filter')
* Frellwit's Swedish Filter

Reports here:
https://github.com/AdguardTeam/AdguardFilters/issues/31097
https://github.com/lassekongo83/Frellwits-filter-lists/issues/51/

**Comment by hawkeye116477** [comment] 2019-03-29 20:28
Similar problem with `live-streaming.pl/commvault`

**Comment by THEtomaso** [comment] 2019-03-30 13:40
> `live-streaming.pl/commvault`

Access to that site is also prevented, because of a partially blocked cookie consent, which can't be accepted!

### Problem filters:
* AdGuard Annoyances filter
* Fanboy's Annoyance List
* Fanboy's Cookie List
* Frellwit's Swedish Filter
* I don't care about cookies

### Problem rules:
```
##.cookie-agree
##.cookie-agree:not(body):not(html)
##.cookie-info
##.cookie-info:not(body):not(html)
```

Reports should be filed accordingly.

**Comment by krystian3w** [comment] 2019-03-30 19:27
@okiehsch maybe similar to https://github.com/uBlockOrigin/uAssets/issues/5246

**Comment by okiehsch** [comment] 2019-03-30 19:42
Yes, that is the same issue and it is fixed if you update `uBO-unbreak`.
I can see the form at `kaspersky.com` and `live-streaming.pl`.

**Comment by okiehsch** [comment] 2019-03-30 20:55
It is now also fixed in `EasyPrivacy`.
https://github.com/easylist/easylist/commit/cb7759414a6e3717933586421ef538a39b151ea5

**Closed** 2019-03-30 21:27 UTC
