### ISSUE TITLE
https://outlook.live.com/mail/0/

### ISSUE THREAD

**Issue by D4n2021** [easylist/easylist#20656] opened 2024-11-10 20:17 UTC
#### What happens?

Ad container (with endless loading animation) is present in inbox above the latest received email

#### Screenshot(s) 

![grafik](https://github.com/user-attachments/assets/1b226930-6cd9-4b05-ae1b-dc767f6783bb)

#### Filter lists you're using:

EasyList, EasyPrivacy, Online Malicious URL Blocklist, Peter Lowe’s Ad and tracking server list, EasyList – Other Annoyances, AdGuard – Other Annoyances, uBlock filters – Annoyances

#### Your settings:

Addons like "I don't care about cookies" disabled.

- OS/version: Win10 (22H2 ofc.)
- Browser/version: Firefox 132.0.1
- Ad block extension/version: uBlock Origin 1.60.0

#### Other details:

container only fully disappears with the following filter added in "my filters" (each "*" icon represents a single lower/uppercase letter/or random digit, I guess it's some kind of unique ID, hopefully not unique to every outlook user?):

`outlook.live.com##.*****.*****.*****.*****`

please add it to easylist if possible and if there is a wildcard like that possible.

**Comment by Yuki2718** [comment] 2024-11-13 16:26
I can't reproduce.

**Comment by ntoskrnl11** [comment] 2024-12-02 19:55
I can reproduce, is there anything I can help with to be able to fix this?

**Comment by liamengland1** [comment] 2024-12-02 23:47
Fixed with

```
outlook.live.com##div[data-app-section="MessageList"] > div[class]:empty
outlook.live.com##div[data-app-section="MessageList"] > .customScrollBar .customScrollBar > div > div[style]:has(> div[data-animatable] .ms-Shimmer-container)
```

From adguard list.

**Comment by Yuki2718** [comment] 2024-12-04 14:15
>  is there anything I can help with to be able to fix this?

Right-click on the ad, choose Inspect, take a screenshot of  the DOM tree and share.

@liamengland1 Can you share the DOM too?

**Comment by liamengland1** [comment] 2024-12-05 00:39
@Yuki2718 

<img width="1106" alt="Screenshot 2024-12-04 at 7 37 15 PM" src="https://github.com/user-attachments/assets/f8974c64-922c-4e62-9822-52b087370112">


<details>
<summary>DOM tree</summary>

```
<div style="position: absolute; left: 0px; top: 0px; height: 77px; width: 100%;">
    <div data-animatable="true" class="EeHm8">
        <div>
            <div class="kk1xx lHRXq iIsOF IjQyD">
                <div class="jGG6V">
                    <div class="kDQ0p fz7QX R2TWA g6FFj">
                        <div class="aGclB">
                            <div class="gCSJa">
                                <div class="GTwIg">
                                    <div class="ms-Shimmer-container root-291">
                                        <div style="width: 100%;" class="ms-Shimmer-shimmerWrapper shimmerWrapper-292">
                                            <div class="ms-Shimmer-shimmerGradient shimmerGradient-293"></div>
                                            <div style="width: auto;" class="ms-ShimmerElementsGroup-root root-295">
                                                <div style="width: 60%; min-width: auto;"
                                                    class="ms-ShimmerLine-root root-296"><svg width="2" height="2"
                                                        class="ms-ShimmerLine-topLeftCorner topLeftCorner-297">
                                                        <path d="M0 2 A 2 2, 0, 0, 1, 2 0 L 0 0 Z"></path>
                                                    </svg><svg width="2" height="2"
                                                        class="ms-ShimmerLine-topRightCorner topRightCorner-298">
                                                        <path d="M0 0 A 2 2, 0, 0, 1, 2 2 L 2 0 Z"></path>
                                                    </svg><svg width="2" height="2"
                                                        class="ms-ShimmerLine-bottomRightCorner bottomRightCorner-299">
                                                        <path d="M2 0 A 2 2, 0, 0, 1, 0 2 L 2 2 Z"></path>
                                                    </svg><svg width="2" height="2"
                                                        class="ms-ShimmerLine-bottomLeftCorner bottomLeftCorner-300">
                                                        <path d="M2 2 A 2 2, 0, 0, 1, 0 0 L 0 2 Z"></path>
                                                    </svg></div>
                                                <div style="width: 40%; min-width: auto;"
                                                    class="ms-ShimmerGap-root root-301"></div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="tPzlR ZInq9 JPJ5T"><i data-icon-name="Delete" role="img" aria-label="Remove"
                                        class="kElPw BXibp zjbHu root-302" title="Remove"></i>
                                    <div class="u9fed">
                                        <div class="ms-Shimmer-container root-291">
                                            <div style="width: 100%;"
                                                class="ms-Shimmer-shimmerWrapper shimmerWrapper-292">
                                                <div class="ms-Shimmer-shimmerGradient shimmerGradient-293"></div>
                                                <div style="width: auto;" class="ms-ShimmerElementsGroup-root root-295">
                                                    <div style="width: 45px; min-width: 45px;"
                                                        class="ms-ShimmerLine-root root-296"><svg width="2" height="2"
                                                            class="ms-ShimmerLine-topLeftCorner topLeftCorner-297">
                                                            <path d="M0 2 A 2 2, 0, 0, 1, 2 0 L 0 0 Z"></path>
                                                        </svg><svg width="2" height="2"
                                                            class="ms-ShimmerLine-topRightCorner topRightCorner-298">
                                                            <path d="M0 0 A 2 2, 0, 0, 1, 2 2 L 2 0 Z"></path>
                                                        </svg><svg width="2" height="2"
                                                            class="ms-ShimmerLine-bottomRightCorner bottomRightCorner-299">
                                                            <path d="M2 0 A 2 2, 0, 0, 1, 0 2 L 2 2 Z"></path>
                                                        </svg><svg width="2" height="2"
                                                            class="ms-ShimmerLine-bottomLeftCorner bottomLeftCorner-300">
                                                            <path d="M2 2 A 2 2, 0, 0, 1, 0 0 L 0 2 Z"></path>
                                                        </svg></div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="qMoQJ xdcYv jYCdC S2l8L">
                                <div class="d6BS2 g6FFj gy2aJ U2XB8 S2l8L">
                                    <div class="ms-Shimmer-container root-291">
                                        <div style="width: 100%;" class="ms-Shimmer-shimmerWrapper shimmerWrapper-292">
                                            <div class="ms-Shimmer-shimmerGradient shimmerGradient-293"></div>
                                            <div style="width: auto;" class="ms-ShimmerElementsGroup-root root-295">
                                                <div style="width: 60%; min-width: auto;"
                                                    class="ms-ShimmerLine-root root-296"><svg width="2" height="2"
                                                        class="ms-ShimmerLine-topLeftCorner topLeftCorner-297">
                                                        <path d="M0 2 A 2 2, 0, 0, 1, 2 0 L 0 0 Z"></path>
                                                    </svg><svg width="2" height="2"
                                                        class="ms-ShimmerLine-topRightCorner topRightCorner-298">
                                                        <path d="M0 0 A 2 2, 0, 0, 1, 2 2 L 2 0 Z"></path>
                                                    </svg><svg width="2" height="2"
                                                        class="ms-ShimmerLine-bottomRightCorner bottomRightCorner-299">
                                                        <path d="M2 0 A 2 2, 0, 0, 1, 0 2 L 2 2 Z"></path>
                                                    </svg><svg width="2" height="2"
                                                        class="ms-ShimmerLine-bottomLeftCorner bottomLeftCorner-300">
                                                        <path d="M2 2 A 2 2, 0, 0, 1, 0 0 L 0 2 Z"></path>
                                                    </svg></div>
                                                <div style="width: 40%; min-width: auto;"
                                                    class="ms-ShimmerGap-root root-301"></div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="qMoQJ xdcYv jYCdC S2l8L">
                                <div class="d6BS2 g6FFj gy2aJ U2XB8 S2l8L">
                                    <div class="ms-Shimmer-container root-291">
                                        <div style="width: 100%;" class="ms-Shimmer-shimmerWrapper shimmerWrapper-292">
                                            <div class="ms-Shimmer-shimmerGradient shimmerGradient-293"></div>
                                            <div style="width: auto;" class="ms-ShimmerElementsGroup-root root-295">
                                                <div style="width: 90%; min-width: auto;"
                                                    class="ms-ShimmerLine-root root-296"><svg width="2" height="2"
                                                        class="ms-ShimmerLine-topLeftCorner topLeftCorner-297">
                                                        <path d="M0 2 A 2 2, 0, 0, 1, 2 0 L 0 0 Z"></path>
                                                    </svg><svg width="2" height="2"
                                                        class="ms-ShimmerLine-topRightCorner topRightCorner-298">
                                                        <path d="M0 0 A 2 2, 0, 0, 1, 2 2 L 2 0 Z"></path>
                                                    </svg><svg width="2" height="2"
                                                        class="ms-ShimmerLine-bottomRightCorner bottomRightCorner-299">
                                                        <path d="M2 0 A 2 2, 0, 0, 1, 0 2 L 2 2 Z"></path>
                                                    </svg><svg width="2" height="2"
                                                        class="ms-ShimmerLine-bottomLeftCorner bottomLeftCorner-300">
                                                        <path d="M2 2 A 2 2, 0, 0, 1, 0 0 L 0 2 Z"></path>
                                                    </svg></div>
                                                <div style="width: 10%; min-width: auto;"
                                                    class="ms-ShimmerGap-root root-301"></div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
```

</details>

Testing on new profile only `outlook.live.com##div[data-app-section="MessageList"] > .customScrollBar .customScrollBar > div > div[style]:has(> div[data-animatable] .ms-Shimmer-container)` from Adguard is needed to hide the adspace

**Closed** 2024-12-05 10:29 UTC
Labels: Easylist
