### ISSUE TITLE
https://www.splcenter.org/fighting-hate/extremist-files/individual/david-duke

### ISSUE THREAD

**Issue by rthfhgyhy567** [easylist/easylist#19752] opened 2024-08-06 18:07 UTC
![image](https://github.com/user-attachments/assets/ff642a80-5d1d-4860-bfa5-46e27d950a43)

**Comment by Khrin** [comment] 2024-08-06 22:31
Duplicate of https://github.com/easylist/easylist/issues/19653

**Closed by Khrin** 2024-08-06 22:31 UTC
Labels: Duplicate, Invalid

**Comment by rthfhgyhy567** [comment] 2024-08-07 01:52
Why exactly did you mark this as "not planned"?  Is this newsletter pop up not able to be blocked without breaking the site or are putting your personal beliefs ahead of your volunteer duties to help filter out content that is annoying?

**Comment by rthfhgyhy567** [comment] 2024-08-07 16:45
![image](https://github.com/user-attachments/assets/762e9be9-4d72-4ad7-9bdd-aa8a5745ad17)

Here is the element of the donation pop up annoyance.  Filtering it does not affect the ability to use the rest of the website.  Since there is no technical reason why adding this to the filter list,[ as it clearly meets the criteria](https://github.com/easylist/easylist/blob/master/README.md), I would have to assume that you are just taking a political stance here.  According to the above link, there are no specific policies regarding annoyances on political websites such as [splcenter.org](splcenter.org).  So the fact that you are deliberately allowing donation pop ups on this website is a form of manipulation and malpractice, because content from several right winged sites are a part of the filter list.  If you have any sense of decency you would open this ticket back up and correctly solve it instead of taking political sides.
