### ISSUE TITLE
uBO CNAME issues (on going)

### ISSUE THREAD

**Issue by ryanbr** [easylist/easylist#5039] opened 2020-03-02 08:14 UTC
**`meteor.com`**
https://forums.lanik.us/viewtopic.php?f=64&t=44369

https://github.com/easylist/easylist/commit/3770907bff7ed4fa2fb640a94e20af2be73be4c3
https://github.com/easylist/easylist/commit/a435ae3798bab2e77da4edf1e8789b5aa6b92ff8

**Comment by ryanbr** [comment] 2020-03-02 09:10
**`cedexis.net / cedexis.com`**

https://github.com/uBlockOrigin/uAssets/issues/7012

**Comment by ryanbr** [comment] 2020-03-02 21:06
**`gstaticadssl.l.google.com`**
https://github.com/uBlockOrigin/uBlock-issues/issues/922
https://github.com/easylist/easylist/commit/f68c1cfc7f3d62def35dc2e6ed766af1c3e56a44

**Comment by mapx-** [comment] 2020-03-04 10:44
https://forums.lanik.us/viewtopic.php?p=153250#p153250

https://github.com/uBlockOrigin/uAssets/commit/6853797579b2cc9848b7a31eb2ab2d3bf4fd140f

**Comment by ryanbr** [comment] 2020-03-04 21:53
**`circularhub.com`**

https://forums.lanik.us/viewtopic.php?f=64&t=44376&p=153272#p153272
https://github.com/easylist/easylist/commit/c6a53879a986b939a8b2904119c012973e874de0

**Comment by mapx-** [comment] 2020-03-07 16:10
https://github.com/uBlockOrigin/uAssets/issues/7071

**Comment by mapx-** [comment] 2020-03-09 18:31
https://github.com/uBlockOrigin/uAssets/issues/7081

**Comment by uBlock-user** [comment] 2020-03-09 20:12
![Capture](https://user-images.githubusercontent.com/21290713/76253187-33044b00-6270-11ea-80b3-672679aa0560.PNG)

`*$script,3p,domain=mp4upload.com` breaks the video.

@ryanbr

**Comment by ryanbr** [comment] 2020-03-19 10:12
**`nikkei.com`**
https://forums.lanik.us/viewtopic.php?f=64&p=153662#p153662

**Comment by ryanbr** [comment] 2020-03-22 08:38
**`leanlab.co`**

https://github.com/uBlockOrigin/uAssets/issues/7117
https://github.com/easylist/easylist/commit/10617611b915e886d5b68c3b31575c9ab29520c6

**Comment by ghajini** [comment] 2020-03-24 19:52
Nsfw xozilla.com
Thumbnails getting blocked

**Comment by mapx-** [comment] 2020-04-01 06:09
https://github.com/uBlockOrigin/uAssets/issues/7181

maybe
`||techtarget.com^$3p` => `||techtarget.com^$~image,3p`

**Comment by ryanbr** [comment] 2020-04-01 07:30
**`techtarget.com`**

Original commit: https://github.com/easylist/easylist/commit/1f0f0a4a785
https://github.com/easylist/easylist/commit/58311419e668d36a3ed004477de5d0dbdc041cfc

**Comment by mapx-** [comment] 2020-04-06 15:58
https://github.com/uBlockOrigin/uAssets/commit/c16d77dc12d2ab7f4eb9ad0f95b47cabc619542b

**cdn13.com**

**Comment by momala454** [comment] 2020-04-10 23:19
mode problems see `https://forums.lanik.us/viewtopic.php?f=91&t=44541&p=154046#p154046`

**Comment by okiehsch** [comment] 2020-04-15 00:47
`https://www.spiegel.de/consent-a-?targetUrl=https%3A%2F%2Fwww.spiegel.de%2F`
https://github.com/NanoMeow/QuickReports/issues/3028#issuecomment-613740227

**Comment by ghajini** [comment] 2020-04-17 10:58
Downlaod blocked 
`https://ddl.to/praviuzc9gqg`
Cname ***cdn13.com***

**Comment by Yuki2718** [comment] 2020-04-18 08:01
`ja.delta.com`
https://forums.lanik.us/viewtopic.php?f=64&t=44570
https://github.com/uBlockOrigin/uAssets/commit/224b73497392f7501e69c95843933db4096445d4

**Comment by momala454** [comment] 2020-04-30 13:39
`tf1.fr` have a cname to cloudfront which is blocked :
https://github.com/easylist/easylist/issues/5298

**Comment by mapx-** [comment] 2020-04-30 14:07
> `tf1.fr` have a cname to cloudfront which is blocked :
> #5298

getting nothing blocked here: `https://www.tf1.fr/tmc/direct`

**Comment by momala454** [comment] 2020-04-30 14:50
> 
> 
> > `tf1.fr` have a cname to cloudfront which is blocked :
> > #5298
> 
> getting nothing blocked here: `https://www.tf1.fr/tmc/direct`

the login button top right is blocked

**Comment by mapx-** [comment] 2020-04-30 14:52
Did you test using the last filters ?

**Comment by momala454** [comment] 2020-04-30 15:08
with the 2 whitelist the login works but the videos still can't be played
`https://www.tf1.fr/tf1/qui-veut-gagner-des-millions/videos/qui-veut-gagner-des-millions-a-la-maison-du-27-avril-2020-08937288.html`

the 2 whitelist should probably be added to this filter
`/^((?!(^https?|^blob):\/\/((ajax|firestore)\.googleapis\.com|(odb|storage|widgets)\.outbrain\.com|(staticxx|www)\.facebook\.com|ak-tf1-das-liv-ssl\.akamaized\.net|api\.(deezer\.com|s10d\.io)|cdn\.streamroot\.io|cdns2\.gigya\.com|cdns\.eu1\.gigya\.com|cdns\.gigya\.com|connect\.facebook\.net|e-cdns-files\.dzcdn\.net|platform\.(instagram\.com|twitter\.com)|players\.edgesuite\.net|([0-9a-z\.\-]+)\.footprint\.net|tf1\.idalgo-hosting\.com|vjs\.zencdn\.net|ws\.facil-iti\.com|www\.(tf1\.fr|wat\.tv))\/).)*$/$script,3p,domain=tf1.fr|wat.tv`

**Comment by TheStinkySkunk** [comment] 2020-04-30 15:14
After reading the TOS, you must register if you do not accept the advertisements that finance the content.

**Comment by mapx-** [comment] 2020-04-30 15:14
the video is running fine on my end

**Comment by momala454** [comment] 2020-04-30 15:17
> 
> 
> @momala454 all fine for me, test using only uBO - no other blocking addon

what are your list subscriptions ?

**Comment by momala454** [comment] 2020-04-30 15:20
when i enable easylist fr the video doesn't work. It work if i disable easylist fr

**Comment by mapx-** [comment] 2020-04-30 15:21
What cname requests are still blocked on your side ?

**Comment by momala454** [comment] 2020-04-30 15:22
whitelisting ` https://cdn.tagcommander.com` seems to fix it

**Comment by mapx-** [comment] 2020-04-30 15:24
`tagcommander` is related to easyprivacy, nothing to do with Liste FR

As I said, tell me what cname requests are still blocked

I have only these cnames still blocked:
![image](https://user-images.githubusercontent.com/10303732/80728615-6d1efa00-8b07-11ea-94fa-bc8be52ffa2a.png)

**Comment by mapx-** [comment] 2020-04-30 15:25
Did you try resetting uBO to default ? Then `purge all caches` and click `update now`

**Comment by momala454** [comment] 2020-04-30 15:29
i am not using any easyprivacy or ublock privacy list.
The request to `https://cdn.tagcommander.com/4183/tc_TF1_20.js` is blocked

the video works only if i add this on my filter
`@@||cloudfront.net^$domain=tf1.fr
@@||g.akamaiedge.net^$script,domain=tf1.fr
@@||cdn.tagcommander.com^$script,domain=tf1.fr`

![image](https://user-images.githubusercontent.com/83005/80729179-21b91b80-8b08-11ea-9270-026b37b69aa5.png)

**Comment by llacb47** [comment] 2020-04-30 15:30
We should not support non-default setup.

**Comment by momala454** [comment] 2020-04-30 15:32
> 
> 
> We should not support non-default setup.

then why there are separated list if we are forced to use only the default parameter ?

**Comment by mapx-** [comment] 2020-04-30 16:26
We can help you if you are using the default setup. 
You disabled some uBO lists, then disabled easyprivacy and instead you are keeping a totally useless list (adblock warning removal). For such warnings enable `ublock filters- annoyances` list

**Comment by momala454** [comment] 2020-04-30 16:29
please merge all lists together then if you don't support non default configuration and prevent adding new filters

**Comment by mapx-** [comment] 2020-04-30 16:39
Liste FR has its own maintainer ( @smed79  ). Nobody knows if he will fix this issue.

Nobody forces you to use the default config .. BUT you can not ask to be helped by the various maintainers if you don't respect this recommendation.  Why ? Simple: we are all volunteers and we cannot test all possible users configurations.

**Comment by momala454** [comment] 2020-04-30 16:41
> we are all volunteers and we cannot test all possible users configurations.

that's why i make bug report to report the problems ...

**Comment by mapx-** [comment] 2020-04-30 16:45
If your issue is the result of a non-standard setup => nobody will add a fix to the official lists, just keep the filters above as custom ones.

**Comment by momala454** [comment] 2020-04-30 16:47
a filter is broken on easylist fr, it should be fixed on easylist fr <__<

**Comment by momala454** [comment] 2020-04-30 16:48
please remove the functionnality to enable custom list as you don't support doing this

**Comment by TheStinkySkunk** [comment] 2020-05-01 05:54
"Why ? Simple: we are all volunteers and we cannot test all possible users configurations."

Seriously, you work free for some company who make M$ ?
Modern Slave Power

**Comment by Yuki2718** [comment] 2020-05-01 05:55
It's simple, you reported the issue to a wrong place. Liste FR issues have to be reported to Liste FR regardless of CNAME. https://forums.lanik.us/viewforum.php?f=91
uBlock Origin (extension) supports custom subscription. uBlock's in-house filter addresses issues arising from default setup which can not be solved by the original filter or which may take time as a temporal solution.

**Comment by momala454** [comment] 2020-05-01 09:57
i posted in the correct location in the first place as tf1.fr have a cname to cloudfront which was blocked due to the filter in liste fr

**Comment by Yuki2718** [comment] 2020-05-01 10:50
> i posted in the correct location in the first place as tf1.fr have a cname to cloudfront which was blocked due to the filter in liste fr

I see you reported to EasyList, but not Liste FR. Although the Liste FR maintainer smed79 was pinged by mapx-, these are separate lists.

**Comment by momala454** [comment] 2020-05-01 11:09
i was talking about the cname change in ublock which broke the filter

**Comment by mapx-** [comment] 2020-05-02 21:27
@smed79 another CNAME (`orange.fr`)
https://github.com/uBlockOrigin/uAssets/commit/621f00b6b8b46364d33ecb112d621c069ebea0bb

**Comment by smed79** [comment] 2020-05-03 18:45
Removed https://hg.adblockplus.org/listefr/rev/a78dd511de0c (unnessary filter).

**Comment by momala454** [comment] 2020-05-14 14:07
CNAME static.afcdn.com ⇒
 dduhv0txi73d1.cloudfront.net

https://www.marmiton.org/recettes/recette_veloute-de-potiron-et-carottes_19009.aspx

**Comment by mapx-** [comment] 2020-05-14 15:11
@smed79

**Comment by Yuki2718** [comment] 2020-06-26 12:21
This is what I myself can't reproduce now, but thought worth reporting. At `https://pornbraze.com` (nsfw) I chose a video and changed to Dood server, then found the video broken. Unfortunately at the time I temporarily disabled EasyList to test my denyallow rules, but the breakage was caused by CNAME seen in the SS below:

![dood](https://user-images.githubusercontent.com/58900598/85856185-833cf400-b7f2-11ea-8175-03ded0bc2b37.png)

This `cdn.jsdelivr.net.cdn.cloudflare.net` is not allowlisted in EasyList too so the result should have been the same if I were using EL, but IDK on what condition it's called - I was using ISP DNS but can't reproduce with the same condition.

**Comment by kulfoon** [comment] 2020-06-28 08:58
Also check this https://github.com/easylist/easylist/issues/5400#issuecomment-636401313

**Comment by gorhill** [comment] 2020-07-12 13:30
Another case: https://www.reddit.com/r/uBlockOrigin/comments/hp7cm8/official_covid19_website_doesnt_work_properly/fxtgw42/

I can't reproduce on my side, but some can, must depend on location. Using `@@||fhi.no^$1p,cname` in uBO reportedly fixes the issue.

**Comment by Yuki2718** [comment] 2020-07-30 14:19
https://github.com/easylist/easylist/pull/5843
https://github.com/easylist/easylist/issues/5845

**Comment by Yuki2718** [comment] 2020-10-09 12:35
https://github.com/uBlockOrigin/uAssets/issues/8015

**Comment by Yuki2718** [comment] 2020-11-05 11:23
https://github.com/easylist/easylist/issues/6360

**Comment by Yuki2718** [comment] 2020-11-20 14:16
https://github.com/uBlockOrigin/uAssets/pull/8249

**Comment by Yuki2718** [comment] 2020-11-30 12:20
https://github.com/uBlockOrigin/uAssets/commit/96a7643db2b129d897dd986d85b42f3273fecf53
(nsfw) `iceporn.com` player broken
<details>
<summary>Screenshot</summary>

![iceporn](https://user-images.githubusercontent.com/58900598/100609720-cd9e4000-3351-11eb-83a8-d14dc1ba5c14.png)

</details>

**Comment by Yuki2718** [comment] 2020-12-04 14:58
https://github.com/easylist/easylist/issues/6596

**Comment by Yuki2718** [comment] 2020-12-21 11:02
https://github.com/uBlockOrigin/uAssets/commit/97d1ca5df867728ca9b110d2a6ef85f922c2a388

**Comment by Yuki2718** [comment] 2021-01-03 09:48
https://github.com/uBlockOrigin/uAssets/commit/377ede788b69ac7aba5c5672378d2051d1232448
@ryanbr It may be better to remove `||cdn13.com^$script,third-party` from EL. So many CNAME issues caused by this.

**Comment by Yuki2718** [comment] 2021-01-27 13:43
https://github.com/uBlockOrigin/uAssets/commit/6f072049fa403134a2ccddad8db0d7510078198f
https://github.com/uBlockOrigin/uAssets/commit/3e4a8dbc0cf59135b19e3ddd2e2812612c1e8497

**Comment by Yuki2718** [comment] 2021-08-11 16:24
https://github.com/easylist/easylist/commit/bf857a790f47ef9e8d465b2c0877add57868b384#commitcomment-54562435
https://github.com/easylist/easylist/commit/6ea6be6503235123c63a4683e7e1b45e71562a4d#commitcomment-54669914

**Comment by Yuki2718** [comment] 2021-08-20 15:39
https://github.com/AdguardTeam/AdguardFilters/commit/76ed4387e95d31af93dcae930cdb3df804f8cfd3

**Comment by Yuki2718** [comment] 2021-08-29 16:23
https://github.com/AdguardTeam/AdguardFilters/issues/92927

**Comment by Yuki2718** [comment] 2021-08-30 10:30
https://github.com/uBlockOrigin/uAssets/commit/2777caad5a6f0e6be49a72b19db59e908f18322f

**Closed** 2022-04-16 03:46 UTC
Labels: uBO-Specific, uBO-CNAME
