### ISSUE TITLE
xHamster sites - Broken (Easylist Cookie List / Fanboy's Annoyance List) [GDPR]

### ISSUE THREAD

**Issue by THEtomaso** [easylist/easylist#12011] opened 2022-05-13 17:03 UTC
### Affected sites:
`https://xhamster.com/` **[NSFW]**

(and a bunch of mirrors)

### Issue:
Elements won't load properly, due to a blocked cookie consent, which now needs to be accepted!

### Screenshot:
Not needed, as the problem is obvious.

### Problem filters:
* **Easylist Cookie List**
* **Fanboy's Annoyance List**

### Problem rule:
`##.cookies-modal:not(body):not(html)`

### Possible fix (for uBO):
`xhamster.*,xhamster1.*,xhamster11.*,xhamster2.*,xhamster5.*,xhamster7.*#@#.cookies-modal:not(body):not(html)`

(At least, this should cover some of the known mirrors, but there are many more)

--

### System info:
* OS/version: Windows 10 Pro (x64)
* Browser/version: Pale Moon v29.4.6 (x64)
* Adblock Extension/version: uBlock Origin v1.16.4.30 (XUL)

**Comment by ryanbr** [comment] 2022-05-13 20:54
We don't use wildcards, also tested https://xhamster2.com/ no issues. Get a "parential" overlay (which can be skipped), but other than that, no issues.

**Comment by THEtomaso** [comment] 2022-05-13 22:14
> We don't use wildcards

Does this mean that ABP-support is back on the table for your cookie filter?
..because several of the fixes that you've applied for it lately has contained uBO-only syntaxes.
E.g. these:
https://github.com/easylist/easylist/issues/10035#issuecomment-999637445
https://github.com/easylist/easylist/issues/10330#issuecomment-1004250051
https://github.com/easylist/easylist/issues/10397#issuecomment-1010675914

--

> Get a "parential" overlay (which can be skipped)

Yes, exactly, but there's no obvious button to press!
A whitelisting will eliminate the confusion.

**Comment by Yuki2718** [comment] 2022-05-14 14:04
https://github.com/AdguardTeam/AdguardFilters/commit/947445d8f40a188677dc8ce401aefdd5ef5bc3bf#commitcomment-73583708

**Comment by Yuki2718** [comment] 2022-05-14 14:06
Wildcard => maybe exapand to .com and .desi.

**Comment by THEtomaso** [comment] 2022-05-14 15:44
@Yuki2718:

This rule needs to be disabled in **uBO Legacy**, in order to see the logical-to-click cookie dialog again!:

https://github.com/AdguardTeam/AdguardFilters/commit/a5047c65876dd99d4dc81001763a981149628c5a#diff-4242d8ca02b02c727d49f104f6a755388e5713822779c8b08aa1bdc29061305eR7252

**Comment by Yuki2718** [comment] 2022-05-14 15:47
@THEtomaso Is adding `megaxh.com,xhwide1.com,xhamster16.*,hamsterix.*,xhplanet1.com,xhamster13.*,xhamster18.*,xhamster19.*,xhamster11.*,xhamster5.*,xhamster10.*,xhamster4.*,xhamster3.*,xhamster2.*,xhamster.*#@#.cookies-modal` to legacy enough?

**Comment by THEtomaso** [comment] 2022-05-14 15:55
Yes.
I disabled it like this though, which also worked:
`megaxh.com,xhwide1.com,xhamster16.*,hamsterix.*,xhplanet1.com,xhamster13.*,xhamster18.*,xhamster19.*,xhamster11.*,xhamster5.*,xhamster10.*,xhamster4.*,xhamster3.*,xhamster2.*,xhamster.*#@$#.cookies-modal { display: none !important; }`

**Comment by Yuki2718** [comment] 2022-05-14 15:57
Well, AG Annoyances is not default list but there's no way to exclude only legacy on AG side. I have to ask what to do to other members.

**Comment by THEtomaso** [comment] 2022-05-14 15:57
Guess it can be added to uBO's Legacy filter, unless you've got a better idea.

**Comment by THEtomaso** [comment] 2022-05-14 16:28
> https://github.com/uBlockOrigin/uAssets/commit/0189e861b4aeae0884136716a91d0b164628d906 👍 

Might just as well add this one too:
`megaxh.com,xhwide1.com,xhamster16.*,hamsterix.*,xhplanet1.com,xhamster13.*,xhamster18.*,xhamster19.*,xhamster11.*,xhamster5.*,xhamster10.*,xhamster4.*,xhamster3.*,xhamster2.*,xhamster.*#@#.cookies-modal:not(body):not(html)`
..to fix the same issue, caused by **Easylist Cookie List**.

**Comment by Yuki2718** [comment] 2022-05-14 16:33
If I understand correctly, it also matters to ABP so should be fixed in ELC (with additional rules to its uBO sublist for non-legacy). The issue is still open.

**Comment by Yuki2718** [comment] 2022-05-14 16:41
(temp) fixed anyway as the site is popular.

**Comment by THEtomaso** [comment] 2022-05-14 16:41
Like I pointed out in my second post; I'm somewhat confused about ryanbr's policy in regards to keeping ELCL ABP-compatible.
Need to hear what he has to say about it.

**Comment by ryanbr** [comment] 2022-05-22 01:45
Reviewed it on FF and Chrome, seems pretty minor. Happy to leave it since there is an easy work around (literally click anywhere on the screen and it'll show the content)

**Closed by ryanbr** 2022-05-22 01:45 UTC
