### ISSUE TITLE
Brave shields are blocking streams when `ads3.xumo.com` loads 

### ISSUE THREAD

**Issue by 2VNews** [easylist/easylist#14222] opened 2022-11-24 07:36 UTC
### List the website(s) you're having issues:
`2vnews.com`
`tklist.us`

### What happens?
Brave shields are blocking streams when `ads3.xumo.com` `https://ads3.xumo.com/` loads.

See the problem here:
`https://2vnews.com/testbraveshieldblocking.php`
`https://tklist.us/testbraveshieldblocking.php`

### List Subscriptions you're using:
none

Brave shields
### Your settings

- OS/version: Windows 10/Latest
- Browser/version: Brave/Latest
- Adblock Extension/version: Brave Shields/Latest

### Other details:

![vizioblocked](https://user-images.githubusercontent.com/48508111/203721413-3b03ebba-5fc1-4254-8b6a-4a9ed84bca74.png)
![redboxblocked](https://user-images.githubusercontent.com/48508111/203721414-cf5e08e2-c120-4ce6-8f31-805da0c2610a.png)
![xumoblocked](https://user-images.githubusercontent.com/48508111/203721415-2b4d6242-159b-45f0-8d8d-0879ee1bc493.png)

**Comment by krystian3w** [comment] 2022-11-24 10:07
Duplicate of #14195

**Closed** 2022-12-18 04:30 UTC
