### ISSUE TITLE
GameReactor.* - Blocked videos (EasyList)

### ISSUE THREAD

**Issue by THEtomaso** [easylist/easylist#3600] opened 2019-06-11 00:22 UTC
### Affected sites:
```
https://www.gamereactor.asia/
https://www.gamereactor.cn/
https://www.gamereactor.de/
https://www.gamereactor.dk/
https://www.gamereactor.es/
https://www.gamereactor.eu/
https://www.gamereactor.fi/
https://www.gamereactor.fr/
https://www.gamereactor.it/
https://www.gamereactor.nl/
https://www.gamereactor.no/
https://www.gamereactor.pl/
https://www.gamereactor.pt/
https://www.gamereactor.se/
```

### Issue:
The rules to block pre-roll ads also prevents video playback.

### Example:
`https://www.gamereactor.eu/video/`

### Screenshot (Blocked video):
![filterissue-gamereactor1](https://user-images.githubusercontent.com/9382674/59235008-a3057800-8bef-11e9-8ec8-9345fbbf83c7.jpg)

### Problem filter:
* EasyList

### Problem rules:
```
/delivery/fc.
/openx.$domain=~openx.tv
/www/delivery/*
```

### Elaboration:
A new rule is needed, to bypass the ads and allow video playback.

### Note (additional issue):
If you browse the sites, and open a few articles, a interstitial ad will appear.
It would be nice if this could be bypassed too.

### Screenshot (interstitial ad):
![filterissue-gamereactor2](https://user-images.githubusercontent.com/9382674/59235023-badcfc00-8bef-11e9-9416-2c9fbade7f86.jpg)

--

* OS/version: Windows 8.1 Pro (x64)
* Browser/version: Pale Moon v28.5.2 (x64)
* Adblock Extension/version: uBlock Origin v1.16.4.11 (XUL)

**Comment by THEtomaso** [comment] 2019-06-11 14:28
@okiehsch:
Something for uBO filters perhaps?

**Comment by okiehsch** [comment] 2019-06-11 20:37
If I go to 
`https://www.gamereactor.eu/video/`
I get redirected to
````
https://www.gamereactor.eu/video/447173/Trials+of+Mana+Remake+Collection+of+Mana+Reveal+Trailer
````
and the video starts playing immediately.

**Comment by THEtomaso** [comment] 2019-06-11 21:30
Must be some regional differences at work again then.

From my end, the **EasyList** rules breaks video playback for ALL of the GameReactor domains!
However, if I disable the problematic rules, like this:
```
/delivery/fc.$badfilter
/openx.$domain=~openx.tv,badfilter
/www/delivery/*$badfilter
```
..then I get the following results:
```
https://www.gamereactor.asia/video/ = No ads
https://www.gamereactor.cn/video/   = No ads
https://www.gamereactor.de/video/   = No ads
https://www.gamereactor.dk/video/   = Ads
https://www.gamereactor.es/video/   = No ads
https://www.gamereactor.eu/video/   = Ads
https://www.gamereactor.fi/video/   = Ads
https://www.gamereactor.fr/video/   = No ads
https://www.gamereactor.it/video/   = No ads
https://www.gamereactor.nl/video/   = No ads
https://www.gamereactor.no/video/   = Ads
https://www.gamereactor.pl/video/   = No ads
https://www.gamereactor.pt/video/   = No ads
https://www.gamereactor.se/video/   = Ads
```
No matter which domain I visit, the videos are fetched from `gamereactor.dk`.

@DandelionSprout:
Since we're in the same region, would you mind taking a look at this issue?

PS:
If you're using '**hpHosts' Ad and tracking servers**' and/or '**Schacks Adblock Plus liste**', you need to add this `$badfilter` rule too:
`||openx.gamereactor.dk^$badfilter`

**Comment by DandelionSprout** [comment] 2019-06-12 00:43
As a resident of the Kingdom of Norway, I can confirm the breakage of `https://www.gamereactor.no/grtv/447213/New+Super+Luckys+Tale+E3+Trailer/` and `https://www.gamereactor.se/grtv/447213/New+Super+Luckys+Tale+E3+Trailer/`.
![image](https://user-images.githubusercontent.com/22780683/59315178-f394d800-8cb8-11e9-8520-5a8fd7ddaa82.png)

This appears to me to be due to a relatively clever choice by `Gamereactor` to *not* load the actual video before it has loaded the preroll ad, making this too difficult even for me to attempt to work around as I can't use my expertise in writing hiding rules for it.

Using the latter example page as my testing ground, so that I could piggyback onto Frellwit's Swedish Filters to see if he had written a fix for it (and if he had, to copy the entries into my list with only minor modifications), it appears that he hasn't. He's written entries to remove the ads during the 5sec waiting period (when using the *$badfilter* entries above), but not for unbreaking EasyList's `openx` breakage.

Making matters even more difficult for testing purposes, is that sometimes upon loading a video page they roll `openx` preroll ads, while other times they seemingly don't and the video starts straight away. I have not been able to find a consistent pattern in either direction, despite 20min of trying to find one.

**Comment by okiehsch** [comment] 2019-06-12 03:53
OK, I tried 
````
https://www.gamereactor.no/video/447213/New+Super+Luckys+Tale+E3+Trailer/
````
with a non norwegian IP and your list enabled and the video is indeed permanently broken on my end using Chromium/Chrome.
This is caused by 
`||gamereactor.*/lay/js/managebanners.js^$important,script`
in your list as far as I can see.

**Comment by DandelionSprout** [comment] 2019-06-12 04:29
I must indeed admit that my list's `Gamereactor` entries are pretty much copies of the ones that were in Frellwit's list ~18 months ago, and that they're far overdue for an update on my end, regardless of whether this issue report had been created or not.

**Comment by THEtomaso** [comment] 2019-06-12 05:06
> Try adding
> `||gamereactor.*/lay/js/managebanners.js^$important,script,badfilter`

The correct entry would actually be this:
`||gamereactor.*/lay/js/manageBanners.js^$script,important,badfilter`
..but this doesn't matter at all, from my end.
It's the **EasyList** rules (which I've pointed out before) that breaks the videos, not DandelionSprout's rule!

**Comment by okiehsch** [comment] 2019-06-12 05:19
![image](https://user-images.githubusercontent.com/16838044/59325168-43d46000-8ce2-11e9-8593-7a1d8d10e5af.png)
![image](https://user-images.githubusercontent.com/16838044/59325204-6cf4f080-8ce2-11e9-94cf-b29ed72602b6.png)

**Comment by DandelionSprout** [comment] 2019-06-12 05:28
I've now commited a pretty large update of my list's `Gamereactor` entries, directly based on Frellwit's entries.

If the commit doesn't fix the problem, then it's probably on EasyList's end; since if the problem was in my list *and* the commit didn't fix it, it'd mean that Frellwit's list would've had the same problem all along for months when visiting `gamereactor.se`, which'd be unlikely.

**Comment by okiehsch** [comment] 2019-06-12 05:38
The video
`https://www.gamereactor.se/grtv/447213/New+Super+Luckys+Tale+E3+Trailer`
is permanently broken if I enable tthe swedish regional list.

@DandelionSprout 
1. Go to `https://www.gamereactor.no/video/447213/New+Super+Luckys+Tale+E3+Trailer`
2. Disable your regional list.
3. Reload the page
4. Click the video or reload the page one more time

Is the video still broken on your end?

**Comment by DandelionSprout** [comment] 2019-06-12 05:51
Upon testing your (okiehsch) scenario above, I am in fact able to confirm that you are in fact right, but with one important caveat.

On `.no` and `.dk`, reloading the page leads me to an interstition page that'd normally be used to display an ad. On `.eu` the interstition page is in fact skipped after a split-second, and I can't figure out which list/entry/extension that causes such a positive effect.

**Comment by okiehsch** [comment] 2019-06-12 05:54
If I enable your list and leave 
`||gamereactor.*/lay/js/managebanners.js^$important,script`
untouched.
A different fix working on my end is
````
gamereactor.*##+js(nano-setTimeout-booster.js)
@@||openx.gamereactor.dk/www/delivery/fc.php$xhr,domain=gamereactor.no
||media.gamereactor.dk/prerolls/*$media,redirect=noopmp4-1s,domain=gamereactor.no
````

**Comment by lassekongo83** [comment] 2019-06-12 07:10
`redirect=noopmp3-0.1s` can be used instead. Then there's no need for the booster.

**Comment by Khrin** [comment] 2019-06-12 10:48
@THEtomaso : With a norwegian IP address and using Firefox and ABP or Ublock origin I don't have any video issues on `gamereactor.no` and all start regularly.

**Comment by krystian3w** [comment] 2019-06-12 16:14
@lassekongo83  tested rewrite in ABP? Also support 0.1s mp3 file.

**Comment by lassekongo83** [comment] 2019-06-12 16:31
That's something https://github.com/abp-filters/abp-filters-anti-cv can use. I only write filters for uBO.

**Comment by krystian3w** [comment] 2019-06-12 16:32
`rewrite` I suppose still works for any subscribed lists.

**Comment by THEtomaso** [comment] 2019-06-12 16:55
With the latest filter updates, I get these results:

```
Chromium-ungoogled:

https://www.gamereactor.asia/video/ = Playback still broken!
https://www.gamereactor.cn/video/   = Playback still broken!
https://www.gamereactor.de/video/   = Playback still broken!
https://www.gamereactor.dk/video/   = "Spring over" activates by itself, and the videos play.
https://www.gamereactor.es/video/   = Playback still broken!
https://www.gamereactor.eu/video/   = Playback still broken!
https://www.gamereactor.fi/video/   = Playback still broken!
https://www.gamereactor.fr/video/   = Playback still broken!
https://www.gamereactor.it/video/   = Playback still broken!
https://www.gamereactor.nl/video/   = Playback still broken!
https://www.gamereactor.no/video/   = "Hopp over" activates by itself, and the videos play.
https://www.gamereactor.pl/video/   = Playback still broken!
https://www.gamereactor.pt/video/   = Playback still broken!
https://www.gamereactor.se/video/   = "Hoppa" activates by itself, and the videos play.
```
```
Pale Moon:

https://www.gamereactor.asia/video/ = Playback still broken!
https://www.gamereactor.cn/video/   = Playback still broken!
https://www.gamereactor.de/video/   = Playback still broken!
https://www.gamereactor.dk/video/   = Videos play, but only after cliking on "Spring over".
https://www.gamereactor.es/video/   = Playback still broken!
https://www.gamereactor.eu/video/   = Playback still broken!
https://www.gamereactor.fi/video/   = Playback still broken!
https://www.gamereactor.fr/video/   = Playback still broken!
https://www.gamereactor.it/video/   = Playback still broken!
https://www.gamereactor.nl/video/   = Playback still broken!
https://www.gamereactor.no/video/   = Videos play, but only after cliking on "Hopp over".
https://www.gamereactor.pl/video/   = Playback still broken!
https://www.gamereactor.pt/video/   = Playback still broken!
https://www.gamereactor.se/video/   = Videos play, but only after cliking on "Hoppa".
```
The problem rules are still the ones found in EasyList, which I pointed out in the first post.

Screenshots:

![filterissue-gamereactor3](https://user-images.githubusercontent.com/9382674/59370703-68acef80-8d43-11e9-896a-cd1fcc24724e.jpg)
![filterissue-gamereactor4](https://user-images.githubusercontent.com/9382674/59370704-68acef80-8d43-11e9-8679-160cf96dd5d0.jpg)
![filterissue-gamereactor5](https://user-images.githubusercontent.com/9382674/59370705-68acef80-8d43-11e9-9589-2b7618f57205.jpg)

**Comment by ryanbr** [comment] 2019-08-17 09:56
Closing this, I don't see this being worked out.

**Closed by ryanbr** 2019-08-17 09:56 UTC
