### ISSUE TITLE
Tomshardware.com

### ISSUE THREAD

**Issue by patrickhgb** [easylist/easylist#5656] opened 2020-07-02 16:35 UTC
### List the website(s) you're having issues:

 `https://www.tomshardware.com/news/sticky-amd-ryzen-processor-proartist-bracket-fix`
 `https://www.tomshardware.com/news/sticky-amd-ryzen-processor-proartist-bracket-fix`

### What happens?

When javascript is enabled, it always force redirect to this anti adblock site: https://www.tomshardware.com/cc.html

### stock settings, ublock origin

- OS/version: windows 10
- Browser/version: firefox latest version as we speak
- Adblock Extension/version:  latest version as we speak

**Comment by ndmgzpmg** [comment] 2020-07-03 15:39
No ads or redirects here.
Using Firefox v68.10.0 on Android 9 with uBlock origin v1.27.10
Proof: `https://imgur.com/a/OySzpKj`

**Comment by llacb47** [comment] 2020-07-03 15:40
Anti-adblock is not fixed in easylist.

**Comment by ndmgzpmg** [comment] 2020-07-04 04:01
I just let easylist on here with uBlock origin and disabled every other list and let just the default settings, including Firefox ETP, still got no redirects, what adblock extensions and lists are you guys using? 
Maybe it just works on desktops?
I can't reproduce it there.

**Comment by an94baller** [comment] 2020-07-05 14:08
Try desktop.

I have 4chan X as a violentmonkey userscript but I don't think it actually affects anything here.

**Comment by ndmgzpmg** [comment] 2020-07-05 17:21
Sadly I can't use a proper environment to test it, mostly because I don't have a computer with me right now, but I tried with the request desktop version from Mozilla which is (maybe) similar to, still got no redirects, uBlock Origin with Firefox, no ETP enabled (to not interfere) and no options changed on uBlock Origin, just easylist and easyprivacy enabled.
Proof:
`https://imgur.com/a/kW5sdAH`

**Comment by ndmgzpmg** [comment] 2020-07-05 17:43
I saw an interesting script getting loaded from vanilla CDN. The website contains some trackers (apparently) that aren't even blocked by easyprivacy!
`https://imgur.com/a/2v3K1FS`
Blocking the whole CDN makes images not loading but blocking just the scripts, everything works fine and it's blocked on all pages from the website apparently.
As it follows:
`||vanilla.futurecdn.net/tomshardware/190026/media/shared/js/btomshardware-gb.js$script,domain=www.tomshardware.com`
Can someone test it and confirm if the adblock redirect is still up even with this script getting blocked?

**Comment by an94baller** [comment] 2020-07-05 21:50
Hey, I tried

||vanilla.futurecdn.net/tomshardware/190026/media/shared/js/btomshardware-gb.js$script,domain=www.tomshardware.com

But it doesn't seem to be working.

This is with only tomshardware.com domain allowed to have javascript running

https://i.imgur.com/YtFBnvC.png

**Comment by llacb47** [comment] 2020-07-06 03:27
@an94baller @patrickhgb Easylist doesn't fix anti-adblock. This is already fixed on default settings in uBlock Origin. If you are still having problems try this filter:
`*-gb.js|$script,1p,important,domain=space.com|laptopmag.com|techradar.com|bikeperfect.com|tomshardware.com|whathifi.com|musicradar.com,redirect=noopjs`

**Comment by ndmgzpmg** [comment] 2020-07-06 05:25
Nice, so that's why I didn't got any redirects even with default settings and just EasyList, that's why uBlock's the best lel.

**Comment by krystian3w** [comment] 2020-07-06 14:23
> Adblock Extension/version: latest version as we speak

> `,redirect=noopjs`

if still use ABP / AdBlock need someting like that:

`$rewrite=abp-resource:blank-js`

**Comment by llacb47** [comment] 2020-07-06 14:37
> > Adblock Extension/version: latest version as we speak
> 
> > `,redirect=noopjs`
> 
> if still use ABP / AdBlock need someting like that:
> 
> `$rewrite=abp-resource:blank-js`

OP is using uBO, they said `stock settings, ublock origin`

**Comment by krystian3w** [comment] 2020-07-06 14:54
So disabled stock list or specifically used text formatting as the h3 tag.

`<h3>List Subscriptions you're using:</h3>` / `### blah blah...`

**Comment by ryanbr** [comment] 2020-07-12 02:20
Yeah, blocking these scripts will cause issues in Easylist

**Closed by ryanbr** 2020-07-12 02:20 UTC
