### ISSUE TITLE
Msn.com: All links blocked!

### ISSUE THREAD

**Issue by dubstepg** [easylist/easylist#2277] opened 2018-11-12 16:40 UTC
Clicking on any link in msn.com closes the tab. Even right-click "Open in a new tab" does not work.

### List the website(s) you're having issues:

```
https://www.msn.com/en-ca/lifestyle/lifestyle-buzz/pippa-middleton-has-named-her-new-baby-and-its-perfectly-fit-for-a-royal/ar-BBPBIMA
```

### What happens?

Go the the above url and click on any link in the article.

### List Subscriptions you're using:

Easylist
Easyprivacy
Anti-circumvention
Acceptable ads

### Your settings

- OS/version: Windows 10 home
- Browser/version: Chrome, Edge, Firefox
- Adblock Extension/version: Adblock 3.34.0

Other extensions: Fullpage Image capture, LastPass, Youtube Downloader

### Other details:

The adblock console shows 

```
/https?:\/\/.*[=|&|%|#|+].*/$popup,domain=0123movies.com|1337x.to|1movies.is|1movies.to|9anime.is|a-o.ninja|adsrt.com|ahlamtv.com|akvideo.stream|allmyvideos.net|animeflv.net|animeid.io|asianvote.com|avgle.com|bittorrent.am|bmovies.to|clipconverter.cc|cloudtime.to|cruzing.xyz|dospelis.com|dropapk.com|egoa....
```

on every click.

I searched easylist and found this commit might be responsible
```
https://github.com/easylist/easylist/commit/6f2ab1bdb9bc25cad183bbc185590458dfacf254
```

**Comment by vlag24** [comment] 2018-11-14 10:19
same here :(

**Comment by dubstepg** [comment] 2018-11-15 00:20
Here is another url where no link opens when I click on it. Can someone please have a look at it?

```
https://www.msn.com/en-ca/entertainment
```

OS: Windows 10
Browser: Edge
Extension: Adblock

cc: @ryanbr @Khrin @monzta

**Comment by smed79** [comment] 2018-11-15 16:26
Install [uBO Extra](https://chrome.google.com/webstore/detail/ublock-origin-extra/pgdnlhfefecpicbbihgmbmffkjpaplco) then check if you still have the same issue.

**Comment by dubstepg** [comment] 2018-11-15 16:42
I am not able to install uBO Extra for Edge or Firefox. I tried on Chrome and I still see the issue in 

```
https://www.msn.com/en-ca/entertainment
```

**Comment by smed79** [comment] 2018-11-15 17:15
test this filter
```
@@|https://www.msn.com^*%$popup,~third-party
```

**Comment by dubstepg** [comment] 2018-11-15 18:03
The above filter does not seem to work.

@vlag24 Were you able to get it working?

**Comment by vlag24** [comment] 2018-11-15 18:07
well, I just deactivate µblock on msn page, it's lazy, I know but it's working for now

**Comment by dubstepg** [comment] 2018-11-15 18:36
@smed79 The above filter is working for me on ublock. But I am not able to get it working on Firefox for some reason.

**Comment by smed79** [comment] 2018-11-15 21:10
> But I am not able to get it working on Firefox for some reason.

Post here the link of an Adblock plus [issue report](https://adblockplus.org/en/getting_started#problems) or screenshot of ublock the [logget](https://github.com/gorhill/uBlock/wiki/The-logger).

**Comment by dubstepg** [comment] 2018-11-16 00:45
@smed79 I realized that the reason ublock was working was because they have added a filter for ublock to revert the easylist change.

```
https://github.com/uBlockOrigin/uAssets/commit/cb7066d435e73ecf006fa668687f9d3fc48f8875
```

**Comment by smed79** [comment] 2018-11-16 02:53
These filters should work for **Adblock plus** users
```
@@||www.msn.com^*%$popup,~third-party
@@||www.bing.com/search?q=$popup,domain=msn.com
```
If not, someone should help by posting an ABP issue report https://adblockplus.org/getting_started#problems

**Comment by dubstepg** [comment] 2018-11-16 03:05
Thanks @smed79 

I was using Adblock in all my browsers. Let me try Adblock plus and report there if there is any issue.

**Comment by smed79** [comment] 2018-11-16 03:41
> I was using Adblock in all my browsers

AdBlock is using Adblock Plus engine

> Let me try Adblock plus

Don't forget to test the filters that i have suggested
You can also, install [uBO Extra](https://chrome.google.com/webstore/detail/ublock-origin-extra/pgdnlhfefecpicbbihgmbmffkjpaplco) to block the anti adblock ads.

**Comment by ryanbr** [comment] 2018-11-16 09:18
I don't see any issues, and it'll only block the popup ads (from "More For You"). I clicked on links from "More From MSN", that works as intended.

**Comment by smed79** [comment] 2018-11-16 11:55
@ryanbr Did you see https://forums.lanik.us/viewtopic.php?p=139728#p139728 ?

**Comment by dubstepg** [comment] 2018-11-16 17:55
@ryanbr I still see issues in the following link. Click on any link and it does not open when I use Adblock.

``
https://www.msn.com/en-ca/entertainment
```

@smed79 Thanks for recommending ubo extra. The page seems very fast now. But I observed that ubo extra is not enough to block ads on msn. I still need ublock to work with it. Since adblock is the industry standard, I am a bit hesitant using ublock.

**Comment by smed79** [comment] 2018-11-16 18:35
> is not enough to block ads on msn

What kind of ads? _(This is the third time i am asking for ABP an issue report !)_

**Comment by ryanbr** [comment] 2018-12-09 04:17
Closing, no further issues.

**Closed by ryanbr** 2018-12-09 04:17 UTC
