### ISSUE TITLE
easylist and easyprivacy scan results: 33% of the domains in rules no longer exist

### ISSUE THREAD

**Issue by jawz101** [easylist/easylist#2374] opened 2018-12-02 16:46 UTC
These took a day to process but let me give a description.  PyFunceble is a tool that can scan hostfile blocklist for dead domains by doing whois lookups, nslookups, etc.  It then spits out detailed reports of the good ones, bad ones, detailed reports of HTTP status codes when attempting to connect to them.

It also has a command to process Adblock+ formatted lists so I tried with Easylists

```
PyFunceble --adblock --link https://easylist.to/easylist/easylist.txt
PyFunceble --adblock --link https://easylist.to/easylist/easyprivacy.txt
```

[easyprivacy.zip](https://github.com/easylist/easylist/files/2637128/easyprivacy.zip)

> Status      Percentage   Numbers     
> ACTIVE      87%          7389        
> INACTIVE    11%         973         
> INVALID     0%           60

[easylist.zip](https://github.com/easylist/easylist/files/2637129/easylist.zip)

> Status      Percentage   Numbers     
> ACTIVE      70%          16741       
> INACTIVE    29%          7080        
> INVALID     0%           90

I'm posting these is because they took a day so I wanted to make sure they were somewhere.  The way it reads is 29% of the domains it checked in the [easylist list no longer exist](https://www.youtube.com/watch?v=pjvQFtlNQ-M).  11% are dead in easyprivacy.  Since they were staggering numbers I wanted to mention it.

In the zips look at /easyxxx/output/hosts/INACTIVE/ and see what domains are dead.
also of interest are the files in /easyxxx/output/Analytic/POTENTIALLY_INACTIVE/ to see what error codes they got.

you can doublecheck them with maybe whois or nslookup

The tool can be found here: https://github.com/funilrys/PyFunceble

**Comment by krystian3w** [comment] 2018-12-02 21:16
> These PyFunceable **is a bit weak**, because it **does not bring everything** out. On the cookie list, he sees **only about 80 domains**, and as the domains are decimated, he has a problem.
> Or, for example:
>   ```
>   ||static.quantcast.mgr.consensu.org/*/cmpui-banner.js$domain=memy.pl|pwn.pl|translatica.pl
>   ```
>
>here should be `memy.pl`, `pwn.pl` and `translatica.pl` on the list of active domains, he does not see it, i.e. lime.
> 

https://github.com/MajkiIT/polish-ads-filter/issues/9324#issuecomment-433860715

**Comment by krystian3w** [comment] 2018-12-02 21:17
> These PyFunceable **is a bit weak**, because it **does not bring everything** out. On the cookie list, he sees **only about 80 domains**, and as the domains are decimated, he has a problem.
> Or, for example:
>   ```
>   ||static.quantcast.mgr.consensu.org/*/cmpui-banner.js$domain=memy.pl|pwn.pl|translatica.pl
>   ```
>
>here should be `memy.pl`, `pwn.pl` and `translatica.pl` on the list of active domains, he does not see it, so a lite pity.
> 

https://github.com/MajkiIT/polish-ads-filter/issues/9324#issuecomment-433860715

**Comment by krystian3w** [comment] 2018-12-03 07:31
Probably the network rules have about 20 domains that would not work all over the world, for such a limitation would also be good to take care of.

**Comment by jawz101** [comment] 2018-12-03 15:22
It just took maybe 12 hours to do this scan so I wanted to pass it along this report because they fail to be recognized by [1,578](https://github.com/funilrys/PyFunceble/blob/master/iana-domains-db.json) registered IANA whois servers.

Closing this since it sounds like it doesn't seem like it's useful information.

**Comment by krystian3w** [comment] 2018-12-03 16:16
You had to leave it open for a example maximum of two months, maybe there are no restoration plans as if some domain has come back to the living.

**Comment by jawz101** [comment] 2018-12-03 16:53
I don't understand why you keep coming up with ideas to devalue the data.  Facts are facts.

I highly doubt 7,000 domains on Easylist just expired in the past 2 months.

**Comment by krystian3w** [comment] 2018-12-03 16:57
On now / now / immediately you probably can not enter it, someone has to test it and the list is actively composed of 10 people?

**Comment by funilrys** [comment] 2018-12-03 17:21
A better practice is to report @krystian3w. But I'll not take it personally. 
Can you please explain your statement ?

```
||static.quantcast.mgr.consensu.org/*/cmpui-banner.js$domain=memy.pl|pwn.pl|translatica.pl
```

Are we understanding the same thing? 

My understanding:
* Block `static.quantcast.mgr.consensu.org/*/cmpui-banner.js` if it's called in the following list of domain:
  * memy.pl
  * pwn.pl
  * translatica.pl

Which mean that with your way of thinking, those list of domains could potentially be false positive. Right ?

**Comment by jawz101** [comment] 2019-01-25 01:09
@krystian3w if I wanted to contribute in a cleanup, what would be the best approach to wok through a contribution?  I'm actually going through the entire easylist and parse out all of the domains (approx. 40,000 unique domains.)  Running it through PyFuncible (validates each domain with nslookups & whois), and then I plan on rerunning the ones it says are invalid several times over a week just to make sure they stay invalid.  Then see if someone else wants to doublecheck it and then work it into a pull request.

**Comment by funilrys** [comment] 2019-01-25 05:57
@jawz101, If syntax check only is needed for the first run you can check that real quick with the `--syntax` argument :wink: (It's literally really quicker :smile_cat: )

**Comment by jawz101** [comment] 2019-01-25 13:52
Well I was parsing out every domain.  I just tried your way & get an error `PyFunceble -ad --syntax -uf https://easylist.to/easylist/easylist.txt`

**Comment by funilrys** [comment] 2019-01-25 14:55
Oh I can reproduce :+1:

**Comment by funilrys** [comment] 2019-01-25 15:08
@jawz101 fix on its way :+1:

**Comment by jawz101** [comment] 2019-02-05 14:40
similar information on dead hosts in Easylist mentioned on [Brave's blog](https://brave.com/the-mounting-cost-of-stale-ad-blocking-rules/).  I submitted a request to remove about 4,963 network rules.  I hoped to do a 2nd pass for the rest of the list but wanted to see if this commit was useful 1st.

**Comment by ryanbr** [comment] 2019-05-12 10:49
Haven't look through this, but trimming the list is time consuming. and must get it right. 

whois / dig records are taken into account of domains? If PyFuncible relys only on whois, it may just fail on weird domain suffix's (which I've seen). Example, .space domains (and probably others)

**Comment by funilrys** [comment] 2019-05-12 11:48
Hi @ryanbr !
I'm currently working on  the 2.0.0 version of PyFunceble which solve and fix a lot of issues including the timing issue by testing as many lines as possible simultaneouly (when asked).

However there is :
* a home page : http://pyfunceble.github.io
* a documentation for the current version : https://pyfunceble.readthedocs.io/en/latest/
* a logic representation flow chart : https://pyfunceble.readthedocs.io/en/latest/logic-representation.html
* and a little explanation from my side about how a test works one the syntax check is done:

1. Try to get the WHOIS record.
2. Could we get the RECORD?
    * YES: Move to point 3.
    * NO: Move to point 4.
3. Could we extract the expiration date from the record?
    * YES: Set the domain as `ACTIVE` and move to the next domain to test.
    * NO: Move to point 4.
4. Try to do a DNS lookup.
5. Do we get an error while trying to run the lookup?
    * YES: Set the domain as `INACTIVE` and move to the next domain to test.
    * NO: Set the domain as `ACTIVE` and move to the next domain to test.

P.S: You can read more about the syntax check by reviewing our `Check()`class [here](https://github.com/funilrys/PyFunceble/blob/master/PyFunceble/check.py)

P.S 2: In the future with the 2.0.0 which will be available into the `dev` version in the coming week(s) we even do a DNS Lookup of every `INVALID` subject before returning the `INVALID` status.

**Comment by ryanbr** [comment] 2019-05-12 12:35
Awesome, I guess we'll see how it goes. Does it parse Easylist/Easyprivacy lists without issue?

**Comment by jawz101** [comment] 2019-05-22 02:49
Let's say it pulls out 27,000 of 30,000 domains and finds that 5,000 of those 27,000 are genuinely dead.

I didn't make the utility and I haven't hand counted  how many it could pull versus how many it does... but why not take a baby step and whittle down the list by 20% and then worry about parsing the leftovers?

**Comment by funilrys** [comment] 2019-05-22 08:20
Hello there,
Sorry, I'm in maintenance mode for the next PyFunceble as I'm expecting it to be out in the next week 😸 

Normally, PyFunceble should be able to parse the list without any issue. I can setup a repo (I'll have a bit of time this weekend normally) just for you at @dead-hosts so you can get your own opinion. 

That way, if something is wrong while parsing we can improve. Otherwise a hosts file or a plain list of domains/IP is working without any issue since I started the project ...

Cheers,
Nissar

**Comment by jawz101** [comment] 2019-07-26 00:46
@funilrys have you added EasyList & EasyPrivacy to @dead-hosts yet?

**Comment by funilrys** [comment] 2019-09-11 19:36
@jawz101 @ryanbr Sorry for the delay :

* https://github.com/dead-hosts/easylist_web_easylist.to 
* https://github.com/dead-hosts/easyprivacy_web_easylist.to/blob/master/info.json

**Comment by funilrys** [comment] 2019-09-11 21:30
@ryanbr:
* https://pyfunceble.readthedocs.io/en/latest/code/logic-representation.html#domain-testing
* https://pyfunceble.readthedocs.io/en/latest/columns/status.html

**Comment by ryanbr** [comment] 2019-09-11 21:37
Would running the script would it hit any limits for dig or whois requests?

**Comment by jawz101** [comment] 2019-12-04 17:12
https://github.com/dead-hosts/easylist_web_easylist.to/blob/master/output/logs/percentage/percentage.txt

```
# File generated by PyFunceble (v2.49.3.dev) / https://github.com/funilrys/PyFunceble
# Date of generation: 2019-12-02T03:31:37.083756

Status      Percentage   Numbers     
----------- ------------ ------------
ACTIVE      75%          29861       
INACTIVE    24%          9866        
INVALID     0%           65   
```

https://github.com/dead-hosts/easyprivacy_web_easylist.to/blob/master/output/logs/percentage/percentage.txt

```
# File generated by PyFunceble (v2.49.3.dev) / https://github.com/funilrys/PyFunceble
# Date of generation: 2019-12-04T16:58:15.956327

Status      Percentage   Numbers     
----------- ------------ ------------
ACTIVE      87%          7517        
INACTIVE    11%          1016        
INVALID     0%           69    
```

**Comment by ryanbr** [comment] 2020-01-12 01:40
@funilrys most of this is now done (for Easylist and Easyprivacy). though there is some domains not being picked up.

Example `zclivukslm.bid` I would suspect many .bid domains would be dead, but they aren't being reported.

Not sure why google domains would be showing like `www.google.com.eg`

Noticed there hasn't been many commit recently, is the project is still active?

**Comment by funilrys** [comment] 2020-01-12 18:09
@ryanbr I'm working on 3.0 ==>  https://github.com/funilrys/PyFunceble/tree/dev ==> https://pypi.org/project/PyFunceble-dev/

@dead-hosts Use PyFunceble-dev :wink:

**Comment by ryanbr** [comment] 2020-01-15 10:04
@dead-hosts @funilrys I notice domains aren't always updated. So if removed, it still sees them. Try to improve the list, but its hard when the scripts keep showing old data

From: `https://raw.githubusercontent.com/dead-hosts/easyprivacy_web_easylist.to/master/output/splited/INACTIVE`

d1clufhfw8sswh.cloudfront.net Doesn't exist. Yet it was scanned today?

**Comment by ryanbr** [comment] 2020-03-10 22:12
Any updates, would like to review fixes for Easylist/Easyprivacy? @dead-hosts @funilrys

**Comment by funilrys** [comment] 2020-03-11 07:44
@ryanbr I deactivate the `inactive_database`. No more old entries will be retested.

**Comment by ryanbr** [comment] 2020-03-11 08:17
Ah great @funilrys , where is the new updated output hosted?

**Comment by jawz101** [comment] 2020-10-09 01:39
Another Brave blog post with tests showing 90% of the rules on Easylist do nothing

https://brave.com/research/

Specifically [Who Filters the Filters: Understanding the Growth, Usefulness and Efficiency of Crowdsourced Ad Blocking](https://brave.com/easylist-sigmetrics-2020/)

> Ad and tracking blocking extensions are among the most popular browser extensions. These extensions typically rely on filter lists to decide whether a URL is associated with tracking or advertising. Millions of web users rely on these lists to protect their privacy and improve their browsing experience. Despite their importance, the growth and health of these filter lists is poorly understood. These lists are maintained by a small number of contributors, who use a variety of undocumented heuristics to determine what rules should be included. These lists quickly accumulate rules over time, and rules are rarely removed. As a result, users’ browsing experiences are degraded as the number of stale, dead or otherwise not useful rules increasingly dwarfs the number of useful rules, with no attenuating benefit. This paper improves the understanding of crowdsourced filter lists by studying EasyList, the most popular filter list. We find that, over its 9 year history, EasyList has grown from several hundred rules, to well over 60,000. We then apply EasyList to a sample of 10,000 websites, and find that 90.16% of the resource blocking rules in EasyList provide no benefit to users, in common browsing scenarios. Based on these results, we provide a taxonomy of the ways advertisers evade EasyList rules. Finally, we propose optimizations for popular ad-blocking tools that provide over 99% of the coverage of existing tools, but 62.5% faster.

**Comment by jawz101** [comment] 2021-03-16 21:35
I just did another check- this time against DNS lookups from Cisco's Umbrella /OpenDNS DNS product.  This is a popular commercial DNS resolver that millions of devices use.  I took the last 30 days of their top 1 million most popular DNS requests, combined them and checked the domains in the EasyList against the list to see if the domains referred to in Easylist are ever hit.

Out of about 28,587 domains referenced in the easylist rules, 19,051 of them no longer get looked up.  Like 66.6% of the domains in the Easylist don't actually fire.


http://s3-us-west-1.amazonaws.com/umbrella-static/index.html

**Comment by chirag127** [comment] 2021-04-17 06:37
> I just did another check- this time against DNS lookups from Cisco's Umbrella /OpenDNS DNS product. This is a popular commercial DNS resolver that millions of devices use. I took the last 30 days of their top 1 million most popular DNS requests, combined them and checked the domains in the EasyList against the list to see if the domains referred to in Easylist are ever hit.
> 
> Out of about 28,587 domains referenced in the easylist rules, 19,051 of them no longer get looked up. Like 66.6% of the domains in the Easylist don't actually fire.
> 
> http://s3-us-west-1.amazonaws.com/umbrella-static/index.html
> 
> My guesstimate is that the Easylist alone could be at least halved simply with some quick work to check if hosts are dead (whois records) or not popular (something like Cisco Umbrella data files).

this is the reason  i use AdGuard easy list optimized. only 27000 rules total

**Comment by ryanbr** [comment] 2021-04-18 04:36
As of Today. we are optimised. https://twitter.com/fanboynz/status/1383401442367610884

```
Status      Percentage   Amount      
----------- ------------ ------------
ACTIVE      100%         38198       
INACTIVE    0%           0          
INVALID     0%           0
```

I run regular checks on redundant filters/domains. 

In size wise
```
Easylist_31-12-2019.txt.gz  (574 KB )
Easylist_18-04-2020.txt.gz  (373 KB)
```
Removed 200 KB (Compressed) is a decent chunk. I use another List because "Easylist isn't optimised" isn't true. 

![EqmrHCcUwAAG4w6](https://user-images.githubusercontent.com/1659004/115134444-387fb780-a064-11eb-9945-5cea1fe47f95.png)

Closing this ticket.

**Closed by ryanbr** 2021-04-18 04:36 UTC
Labels: Work In Progress

**Comment by felix-22** [comment] 2021-10-18 18:45
> ryanbr : As of Today. we are optimised.

Yeah, good work. However only partially / halfly (50%), coz there are as many parked domains as the non-existent ones.

**Comment by jawz101** [comment] 2021-10-18 19:18
OP here- I just want to say this is very impressive work.

@ryanbr @felix-22

I have a suggestion and I may propose it to @funilrys for the PyFunceble utility.  I think I have done so before.  For the past couple of years I've been using the Cisco Umbrella (formerly OpenDNS) Top 1 Million daily DNS lookup reports they publish [here](https://s3-us-west-1.amazonaws.com/umbrella-static/index.html) to evaluate the adaway list.

If you are unfamiliar with OpenDNS, it is a public DNS service which has been around for longer than most other public resolvers which allowed for content filtering and malware/phishing protection.  They make lists of the top 1 million name lookups records publicly available.  _"The OpenDNS Global Network processes an estimated 100 billion DNS queries daily from 85 million users through 25 data centers worldwide."_

So, regardless of if a domain is registered- these are the actual queries made by us in circulation.  If a domain is parked, it's going to be valid but nothing is pointing to it so you'll never see it used.  I will download, say, the past 3 months of logs and if no one has tried to lookup a domain, I pull it from the adaway list.

**Comment by felix-22** [comment] 2021-10-19 10:18
> jawz101 : I have a suggestion and I may propose it to @ funilrys for the PyFunceble utility

Ok, there is a new thread for it: https://github.com/funilrys/PyFunceble/issues/255
