### ISSUE TITLE
instapundit.com [Breakage] 

### ISSUE THREAD

**Issue by CbumDino** [easylist/easylist#17524] opened 2023-10-11 13:10 UTC
#### List the website(s) you're having issues with:
https://instapundit.com/233768/#disqus_thread

#### What happens?
Disqus comments breakage.

#### Screenshot(s) 
<img width="883" alt="Screenshot 2023-10-11 at 15 09 34" src="https://github.com/easylist/easylist/assets/65717387/5d53702f-6737-4e14-ae60-54826aa6093b">

#### Filter lists you're using:
EL EL 

#### Other details:
`instapundit.com#@#.postad`
`instapundit.com#@#.ad-space`

**Comment by monzta** [comment] 2024-06-25 10:27
cannot reproduce, seems to be fixed now

**Closed by monzta** 2024-06-25 10:27 UTC
