### ISSUE TITLE
www.varusteleka.(fi|com) shopping cart

### ISSUE THREAD

**Issue by shnm** [easylist/easylist#6577] opened 2020-12-01 23:35 UTC
### List the website(s) you're having issues:
`https://www.varusteleka.com/en/cart`
`https://www.varusteleka.fi/fi/cart`

### What happens?
In the final steps of an order a customer has to accept the Terms and Conditions and Privacy Notice
Unfortunately the accept box is hidden by the `###privacypolicy` filter

### List Subscriptions you're using:
Broken atleast on:
AdGuard Annoyances
Fanboy’s Annoyance
EasyList Cookie

### Your settings

- OS/version: Windows 10 2004
- Browser/version: Firefox ESR / Chromium
- Adblock Extension/version: uBlock Origin

### Other details:
`###privacypolicy`

**Comment by peace2000** [comment] 2020-12-03 20:10
Yeah, I'll add a fix to this list until it's fixed in those lists.

**Comment by peace2000** [comment] 2020-12-03 20:11
Some screenshots, a mandatory checkbox is being removed:

![kuva](https://user-images.githubusercontent.com/17256841/101082620-659b6400-35b4-11eb-9441-a6d8e16652c9.png)

![kuva](https://user-images.githubusercontent.com/17256841/101082662-7946ca80-35b4-11eb-85fe-67c7d91af3d1.png)

**Comment by peace2000** [comment] 2020-12-03 20:36
To reproduce: start making an order (you can use the English site: https://www.varusteleka.com/en), just use some random values, and then on the last page of order making (summary page) order can't be made because a checkbox is missing.

**Closed** 2020-12-05 02:01 UTC
