### ISSUE TITLE
numerama.com & frandroid.com

### ISSUE THREAD

**Issue by momala454** [easylist/easylist#11789] opened 2022-04-24 21:31 UTC
The following issue has been closed but it's not solved  https://github.com/easylist/easylist/issues/11628

**Comment by ryanbr** [comment] 2022-04-24 23:55
It works for me. Embedded tweets show. @momala454

**Comment by momala454** [comment] 2022-04-25 06:10
they show as text instead of showing as embeded

this with ublock origin enabled : 
![image](https://user-images.githubusercontent.com/83005/165030185-a6111772-7a5f-4282-b329-d522788591f0.png)

this with ublock origin disabled and allowed cookies : 
![image](https://user-images.githubusercontent.com/83005/165030237-4e0e593e-1136-416b-9982-8af49ef3cfa6.png)


maybe it works for you because your ip is not from EU

**Comment by ryanbr** [comment] 2022-05-07 14:27
Closing, rechecked this. no issues.

**Closed by ryanbr** 2022-05-07 14:27 UTC

**Comment by momala454** [comment] 2022-05-07 16:19
The issue is still present, I tested on 3 navigator on windows and android on Firefox with ublock origin. On which country did you tested ? Maybe it's only in Europe or France

**Comment by Khrin** [comment] 2022-05-07 22:37
Check with ubo+ff and no issues. Surely it's caused by another list

**Comment by momala454** [comment] 2022-05-08 07:18
> Check with ubo+ff and no issues. Surely it's caused by another list

With easy privacy and easy list cookie and liste fr?
