### ISSUE TITLE
symbolab.com cookies consent

### ISSUE THREAD

**Issue by meirroth** [easylist/easylist#4967] opened 2020-02-24 21:33 UTC
### List the website(s) you're having issues:

`https://www.symbolab.com/`
### What happens?
Cookies consent message showing

### List Subscriptions you're using:
All the lists in uBlock Origin are active

### Your settings

- OS/version: W10 64bit
- Browser/version: FF 72.0.2 (64-bit)
- Adblock Extension/version: uBlock Origin 1.24.2

### Other details:
[screenshot](https://cdn3.imggmi.com/uploads/2020/2/25/b914a95939631d7fe349db05e6fff7c6-full.png)

**Comment by llacb47** [comment] 2020-02-24 21:38
Generic: `##.nl-cookiepolicy`

**Comment by peace2000** [comment] 2020-02-25 15:27
This is already in the Easylist Cookie list.

**Comment by peace2000** [comment] 2020-02-25 15:33
Ok, now I got it. Ubo's internal filters have this rule:

@@||symbolab.com^$generichide

Which disabled generic hiding rules being appliead to that domain. Dunno why.

**Comment by meirroth** [comment] 2020-02-25 15:44
> This is already in the Easylist Cookie list.
> 
> ![kuva](https://user-images.githubusercontent.com/17256841/75261914-6c5ea480-57f4-11ea-9ce5-935e3d5d850f.png)
> 
> However it doesn't get hid for some reason.

what does it mean ​​​​"0 used out of 16,877" in uBlock? how do i change it?​​
![Annotation 2020-02-25 174246](https://user-images.githubusercontent.com/12494197/75263226-61a50f00-57f6-11ea-943e-29c8906d2764.png)

**Comment by peace2000** [comment] 2020-02-25 20:27
disable that list -> accept changes -> enable that list -> accept changes -> purge cache -> update (wait a moment until all lists are updated).

If still doesn't work then Ubo needs reinstallation probably.

Ubo's internal filters have a rule to disable general filters in order to avoind adblock detection. Easylist probably won't fix problems caused by Ubo's filters but maybe if Easylist itself ads that rule, maybe they will accept a specific hiding rule.

**Comment by peace2000** [comment] 2020-02-25 20:36
https://github.com/easylist/easylist/pull/4974

**Closed** 2020-02-28 12:41 UTC
Labels: Invalid, uBO-Specific
