### ISSUE TITLE
Acceptable Ads $$$$$$

### ISSUE THREAD

**Issue by DanIbba** [easylist/easylist#1763] opened 2018-08-28 12:22 UTC
https://www.ynet.co.il/articles/0,7340,L-5336623,00.html
ABP ("ADBLOCK" Plus)

**Good for you $$$$$$$$$$$$$$$$$$$$$$$$**

![acceptable ads](https://user-images.githubusercontent.com/24211092/44722540-08abcc00-aad6-11e8-8ede-8d5281b15449.png)

well, less than 10% content

**Comment by LanikSJ** [comment] 2018-08-29 00:36
Acceptable Ads is an AdBlock Initiative that has nothing to do with EasyList.

https://adblockplus.org/acceptable-ads

Your "complaint" should be filled at https://adblockplus.org

**Comment by Khrin** [comment] 2018-09-02 13:48
Who helps what? 

I don't have the Acceptable Ads enabled, and using ABP I don't see any unblocked advertisement on this domain, even without using EasyList Hebrew.

Not seeing what's the problem is here, I close this issue report.

**Closed by Khrin** 2018-09-02 13:48 UTC

**Comment by DanIbba** [comment] 2018-09-02 15:34
@Khrin how convenient.. sorry, mate.

**Comment by LanikSJ** [comment] 2018-09-02 22:36
@DanIbba 
![1_ilymgv8farqouqb358pxrg](https://user-images.githubusercontent.com/12159404/44961434-f8289680-aec5-11e8-9ddf-3e7db1490154.jpeg)
