### ISSUE TITLE
swiggy.com ads

### ISSUE THREAD

**Issue by MasterKia** [easylist/easylist#13184] opened 2022-09-02 17:14 UTC
### List the website(s) you're having issues:
`https://swiggy.com`

### What happens?
Go to the site, search for "Delhi" as an address => The list of restaurants has ads (labeled as "Promoted" - first screenshot)

On mobile (second screenshot), these are labeled as "Ad".

### List Subscriptions you're using:
EasyList

### Your settings

- OS/version: Windows
- Browser/version: Firefox
- Adblock Extension/version: uBlock Origin

### Other details:

The second and third filter for mobile.
```
swiggy.com##a[class^="_"][href^="/restaurants"]:-abp-has(div[style="background: rgb(58, 60, 65) none repeat scroll 0% 0%; color: rgb(255, 255, 255); border-color: rgb(30, 32, 35) transparent;"])
swiggy.com##[class^="styles_row"]:-abp-has([class^="styles_imgAd"])
swiggy.com##a[id^="restaurant-card-"]:-abp-has([class^="styles_imgAd"])
```

https://user-images.githubusercontent.com/17685483/188203823-3d630aaf-11e0-4648-8829-d83718c59d95.png

https://user-images.githubusercontent.com/17685483/188203990-92adcf8f-8a06-4734-94da-c7d1dad440bd.png

**Comment by ryanbr** [comment] 2022-09-03 09:47
not really keen on these filters, not able to reproduce also slow filters.

**Comment by MasterKia** [comment] 2022-09-03 09:49
You can't reproduce the first screenshot when searching for Delhi? (with uBO Off)

**Comment by ryanbr** [comment] 2022-09-03 09:53
Self promos also, so closing.

**Closed by ryanbr** 2022-09-03 09:53 UTC

**Comment by MasterKia** [comment] 2022-09-03 09:55
Restaurant owner pays to get higher in the search results.

How can it be **_self_**-promotion if the site owner is being paid by someone else?
